### ISSUE TITLE
DEV: (new confirm popup version) button pages do not update live

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1026]
Installed latest DEV version with new popup.
Updated tft, blueprint, esphome.

Button pages, and device pages (eg. light, fan) do not update state on buttons/sliders. Have to exit page and go back in to see the status of buttons, sliders etc..

Home screen, alarm, climate, and entities pages are unaffected and update live.

BTW, new popup for confirmation looks nice!

**Comment by edwardtfn** [comment]
I believe that is fixed now.
By the way, you can now assign a media player to a button. 😉

**Comment by Doughboy68** [comment]
Confirm this is fixed.

I added media player (homepod mini) to a button, long pressing button shows the player screen but seems that it is not functional yet. Looks good though.

**Comment by edwardtfn** [comment]
No, still no code behind... Hopefully tomorrow. 😃

**Comment by fzambroni** [comment]
Mine is still not working. I just updated it to the last DEV version. The buttons only update after swiping to a different page and back.

**Comment by Doughboy68** [comment]
Make sure the current page sensor is enabled for panel.

If you just updated to dev from main, then this is probably the issue so you have to go and update. The issue in this thread was caused by something else.

Looking at recent code, there should be a notification in HA telling you how to do this.

**Comment by fzambroni** [comment]
Working now. Thanks

**Comment by edwardtfn** [comment]
Have you received the notification on Home Assistant?

**Comment by fzambroni** [comment]
Yes, after the last update. I followed the steps described, and it worked.
