### ISSUE TITLE
Calendar/Schedule icon permanently displayed when using climate entity.

### ISSUE THREAD

**Issue by Plawasan** [Blackymas/NSPanel_HA_Blueprint#1265]
I'm running all 5 of my displays now on 4.1 however I've noticed this issue on two of them even on earlier versions - there is a "stray" mdi:calendar-refresh icon permanently displayed on the home screen, without any (obvious to me) reason for it.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/73796046/e03e1453-bf7c-43c6-b017-7d66f50d11ca)

 I tried to gradually single out what line in my yaml causes it (since I've carried that config over from early versions), as far as I can tell it shows up the moment I add a climate entity, in my case:

```
alias: NSPanel Office
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 0fe7541674415f222c988eb12cddd100
    weather_entity: weather.forecast_stodulky
    outdoortemp: sensor.external_temperature
    climate: climate.atrea_modbus   <---- this line
```

Is this by design or a bug?

**Comment by edwardtfn** [comment]
Since the beginning, the 3rd chips was reserved for the climate entity, while 1st and 2nd are reserved for relays, and the others are customizable.
What changes in v4.0 was the icon shown, which is now based on the state of your climate, which in your case is probably 'scheduled'.

**Comment by Plawasan** [comment]
FWIW, this is what the entity state/attributes look like - nothing suggesting a "scheduled" state

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/73796046/e5ccce3e-8e6d-441c-be5d-2f492805acda)

**Comment by edwardtfn** [comment]
Mmmm
I will have to take a look when back home.

**Comment by edwardtfn** [comment]
I'm trying to duplicate this without success. Probably something missing from my side.

Could you please share your ESPHome yaml so I can duplicate exactly the same here? Please make sure to hide any sensitive info before sharing.

**Comment by Plawasan** [comment]
Sure, should be very standard:

nspanel-office.yaml:

```
substitutions:
  device_name: "nspanel_office" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
packages:
  core_package: !include nspanel_esphome_core.yaml
  upload_tft_package: !include nspanel_esphome_addon_upload_tft.yaml
```

both the included files are taken directly from the 4.2 release, with the only exception of the tft url, which points to my local HA instance which hosts the latest 4.2 tft file (getting that from github never worked for me).

**Comment by edwardtfn** [comment]
Ok, nothing special... I have to investigate a bit more...

**Comment by zimjjan** [comment]
I have the exact same problem here. Green icon showing up permanently on the "third" slot.

**Comment by edwardtfn** [comment]
Could you please go to Developer Tools, tab States, find the climate entity used in your panel and let me know de values for state and for `hvac_action` attribute?

**Comment by zimjjan** [comment]
<img width="1129" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/12293998/d88ed146-74e5-4651-9650-2a70ddb76f16">

**Comment by edwardtfn** [comment]
Ok, last question... 
When you look for this entity on Home Assistant, which icon is shown?
I think I know why that icon is shown but wanna your help to define which icon should be shown.

**Comment by edwardtfn** [comment]
I think on earlier versions it was showing a thermometer with lines, which is probably better than a calendar.

![IMG_6642](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/c2421053-55d6-4daf-b1e5-6377a5c555b4)

One option would be using thermometer-auto, but I whint that might not be very intuitive in all languages.

![IMG_6641](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/afb9d01e-d11c-4c51-a522-6bfed7f9231d)

Please let me know your thoughts.

**Comment by zimjjan** [comment]
<img width="689" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/12293998/491c4508-ac77-4fe7-9cd1-dac7dc097f76">

**Comment by zimjjan** [comment]
Actually, I'd prefer to be able to disable it, as it was before, or at least be able to change the color. 

I do not really get what the icon indicates in the first place.

This is, because I use the other chips to signal a somehow "unnormal" state of other things and it irritates me as soon as one of the chips shows up.

It would be even cooler to also have the option to customize the first 3 slots in addition to the already configurable chips, but that is another option.

**Comment by edwardtfn** [comment]
You have a good point.
I've applied a change to `dev` where the icon will be hidden when it's state is "auto".
Hopefully it will be released soon.

**Comment by edwardtfn** [comment]
I've moved this from v4.2 to v4.1.3, so it will be released a bit earlier (probably in the coming few days).

**Comment by Plawasan** [comment]
Icon is gone, thanks!

**Comment by Plawasan** [comment]
Our friend the calendar icon is back on 4.2.5...

**Comment by edwardtfn** [comment]
I've fixed that again on `dev` and it will be part of the next release.

**Comment by Plawasan** [comment]
Everything updated to 4.2.6, clean ESPHome build, updated blueprint, reloaded automations... and I still see the calendar icon :/

climate entity properties:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/73796046/cf1d187b-737c-4d2e-ae27-50fc0cabe261)

**Comment by edwardtfn** [comment]
I know. Unfortunately the fix isn't released yet. It will be part of v4.3.

**Comment by Plawasan** [comment]
No worries, it's a minor cosmetic issue, just reporting it since I saw it mentioned as fixed in the release notes.
