### ISSUE TITLE
`DEV` Setpoint is not the same as target point for my geothermal heater

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1459]
Hi,

Tested current dev branch and some thoughts. 
- Chips icons does not override with selected icons anymore, but a lightbulb or a switch/door is shown now instead.
- Hardware button indicators does not always show correct state if they are triggered from HA or webserver while screen is on.
- **Climate heating broke for me, as the setpoint is not the same as target point for my geothermal heater. Perhaps a user setting in ESP? When I want to increase one step from 19 to 20 degrees then it is set to 40-50 degrees which is the target heating water temp. and all goes haywire in the basement and extremely hot in the house :)**
- Entities page does not show labels when I have custom names. #1455
- Perhaps we could have a default icon based on UOM if none is entered/overiden for entities? Basics like climate, humidity, power?

_Originally posted by @Floppe in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1456_

**Comment by edwardtfn** [comment]
I've implemented this into `dev` and will be included in the next release soon.
Please feel free to try that before the release and give me some feedback.

**Comment by Floppe** [comment]
Anything I need to configure? It still does not work for my heater. ESP logs has some warnings.

> [08:33:48][D][display.disp1.on_page:703]: Nextion page changed
[08:33:48][D][display.disp1.on_page:704]: New page: climate (6)
[08:33:48][D][text_sensor:064]: 'nspanel-living-room Current page': Sending state 'climate'
[08:33:48][D][script.page_changed:2072]: New page: climate
[08:33:48][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[08:33:48][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[08:33:48][D][sensor:094]: 'nspanel-living-room Page Id': Sending state 6.00000  with 2 decimals of accuracy
[08:33:48][D][sensor.page_id:1335]: New page Id: 6
[08:33:48][W][component:214]: Component display took a long time for an operation (0.17 s).
[08:33:48][W][component:215]: Components should block for at most 20-30ms.
[08:33:49][D][text_sensor:064]: 'nspanel-living-room Detailed Entity': Sending state 'climate.heat'
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:34:18][D][script.timer_page:2840]: Fallback to page Home

Climate attributes:

> hvac_modes: "off", auto
min_temp: 10
max_temp: 40
target_temp_step: 1
current_temperature: 46.3
temperature: 19
hvac_action: heating
friendly_name: Heat
supported_features: 1

NSPanel screen shows 46.3 when I would want it to show 19.

**Comment by edwardtfn** [comment]
```
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
[08:33:49][W][nextion:405]: Nextion reported variable name invalid!
```
Are you still seen these messages on your log?

**Comment by edwardtfn** [comment]
> Climate attributes:

```yaml
hvac_modes: "off", auto
min_temp: 10
max_temp: 40
target_temp_step: 1
current_temperature: 46.3
temperature: 19
hvac_action: heating
friendly_name: Heat
supported_features: 1
```
>NSPanel screen shows 46.3 when I would want it to show 19.

Could you please share a picture of your screen?
This haven't changed that much other than the position the target temperature is shown, but in this case, the current temperature (shown higher in the page) is 46.3C while the target temperature (shown close to the slider) should be showing 19C.

**Comment by edwardtfn** [comment]
> When I want to increase one step from 19 to 20 degrees then it is set to 40-50 degrees which is the target heating water temp.

Is this still happening?

**Comment by Floppe** [comment]
> > Climate attributes:
> 
> ```yaml
> hvac_modes: "off", auto
> min_temp: 10
> max_temp: 40
> target_temp_step: 1
> current_temperature: 46.3
> temperature: 19
> hvac_action: heating
> friendly_name: Heat
> supported_features: 1
> ```
> >NSPanel screen shows 46.3 when I would want it to show 19.
> 
> Could you please share a picture of your screen?
> This haven't changed that much other than the position the target temperature is shown, but in this case, the current temperature (shown higher in the page) is 46.3C while the target temperature (shown close to the slider) should be showing 19C.

![IMG_20240104_084022.jpg](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/238729/22986904-f622-480c-b9f7-6281bf1b93fa)

**Comment by edwardtfn** [comment]
Ok, the 47C is correct, as there is current temperature. This haven't changed on v4.2.
Th3 problem is that other things)including target temp of 19C are not displayed).
I will look at that.
Thanks!

**Comment by edwardtfn** [comment]
By the way, do you see anything in your logs (Home Assistant and ESPHome) that could be useful?

**Comment by Floppe** [comment]
> ```
> [08:33:49][W][nextion:405]: Nextion reported variable name invalid!
> [08:33:49][W][nextion:405]: Nextion reported variable name invalid!
> [08:33:49][W][nextion:405]: Nextion reported variable name invalid!
> [08:33:49][W][nextion:405]: Nextion reported variable name invalid!
> [08:33:49][W][nextion:405]: Nextion reported variable name invalid!
> [08:33:49][W][nextion:405]: Nextion reported variable name invalid!
> ```
> 
> Are you still seen these messages on your log?

Yes, I pulled latest dev now and I still see these. HA logs does not show anything though.

**Comment by edwardtfn** [comment]
Is this happening when you enter the climate page or something else? Could you please expand those logs so we can understand the context?

Also, is this the embedded climate (add-on) or are you using some other climate entity from Home Assistant?

**Comment by Floppe** [comment]
> Is this happening when you enter the climate page or something else? Could you please expand those logs so we can understand the context?
> 
When I enter climate page. Here more logs from ESP.

```
[10:41:14][D][nextion:446]: Got touch event:
[10:41:14][D][nextion:447]:   page_id:      0
[10:41:14][D][nextion:448]:   component_id: 4
[10:41:14][D][nextion:449]:   event type:   PRESS
[10:41:14][D][script.timer_dim:2871]: Waking up on page: home
[10:41:14][D][script.set_brightness:2455]: brightness: 29%
[10:41:14][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[10:41:14][W][component:214]: Component display took a long time for an operation (0.06 s).
[10:41:14][W][component:215]: Components should block for at most 20-30ms.
[10:41:14][D][nextion:446]: Got touch event:
[10:41:14][D][nextion:447]:   page_id:      0
[10:41:14][D][nextion:448]:   component_id: 4
[10:41:14][D][nextion:449]:   event type:   RELEASE
[10:41:14][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[10:41:14][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[10:41:14][D][text_sensor:064]: 'nspanel-living-room NSPanel local event': Sending state '{"page": "home", "component": "climate", "event": "click"}'
[10:41:14][D][text_sensor:064]: 'nspanel-living-room Detailed Entity': Sending state ''
[10:41:14][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "home", "component": "climate", "event": "click"}"
[10:41:14][D][nextion:464]: Got new page: 6
[10:41:14][D][display.disp1.on_page:707]: Nextion page changed
[10:41:14][D][display.disp1.on_page:708]: New page: climate (6)
[10:41:14][D][text_sensor:064]: 'nspanel-living-room Current page': Sending state 'climate'
[10:41:14][D][script.page_changed:2085]: New page: climate
[10:41:14][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[10:41:14][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[10:41:14][D][sensor:094]: 'nspanel-living-room Page Id': Sending state 6.00000  with 2 decimals of accuracy
[10:41:14][D][sensor.page_id:1348]: New page Id: 6
[10:41:14][W][component:214]: Component display took a long time for an operation (0.18 s).
[10:41:14][W][component:215]: Components should block for at most 20-30ms.
[10:41:17][D][text_sensor:064]: 'nspanel-living-room Detailed Entity': Sending state 'climate.heat'
[10:41:17][D][script.set_climate:2480]: Starting
[10:41:17][D][script.set_climate:2481]:   current_temp:         46.900002
[10:41:17][D][script.set_climate:2482]:   supported_features:   1
[10:41:17][D][script.set_climate:2483]:   supported_hvac_modes: 0
[10:41:17][D][script.set_climate:2484]:   target_temp:          19.000000
[10:41:17][D][script.set_climate:2485]:   target_temp_high:     -999.000000
[10:41:17][D][script.set_climate:2486]:   target_temp_low:      -999.000000
[10:41:17][D][script.set_climate:2487]:   temp_step:            10
[10:41:17][D][script.set_climate:2488]:   total_steps:          30
[10:41:17][D][script.set_climate:2489]:   temp_offset:          100
[10:41:17][D][script.set_climate:2490]:   climate_icon:         
[10:41:17][D][script.set_climate:2491]:   embedded_climate:     False
[10:41:17][D][script.set_climate:2493]: Page climate is visible
[10:41:17][D][script.set_climate:2536]: Finished
[10:41:17][W][component:214]: Component api took a long time for an operation (0.13 s).
[10:41:17][W][component:215]: Components should block for at most 20-30ms.
[10:41:17][W][nextion:405]: Nextion reported variable name invalid!
[10:41:17][W][nextion:405]: Nextion reported variable name invalid!
[10:41:17][W][nextion:405]: Nextion reported variable name invalid!
[10:41:17][W][nextion:405]: Nextion reported variable name invalid!
[10:41:17][W][nextion:405]: Nextion reported variable name invalid!
[10:41:17][W][nextion:405]: Nextion reported variable name invalid!
[10:41:21][D][sensor:094]: 'ntc_source': Sending state 1.70400 V with 2 decimals of accuracy
[10:41:21][D][resistance:039]: 'resistance_sensor' - Resistance 11957.9Ω
[10:41:21][D][sensor:094]: 'resistance_sensor': Sending state 11957.89453 Ω with 1 decimals of accuracy
[10:41:21][D][ntc:026]: 'nspanel-living-room Temperature' - Temperature: 21.0°C
[10:41:21][D][sensor:094]: 'nspanel-living-room Temperature': Sending state 21.02960 °C with 1 decimals of accuracy
[10:41:27][D][sensor:094]: 'nspanel-living-room RSSI': Sending state -66.00000 dBm with 0 decimals of accuracy
[10:41:30][I][script.watchdog:3050]: Wi-Fi:         Fair (-66 dBm)
[10:41:30][I][script.watchdog:3070]: API:           Connected
[10:41:30][I][script.watchdog:3088]: Blueprint:     4.2dev.4
[10:41:30][I][script.watchdog:3103]: ESPHome:
[10:41:30][I][script.watchdog:3104]:   Version:     4.2dev.4
[10:41:30][I][script.watchdog:3107]:   Framework:   arduino
[10:41:30][I][script.watchdog:3113]: UART:
[10:41:30][I][script.watchdog:3114]:   Baud rate:   921600 bps
[10:41:30][I][script.watchdog:3115]:   Queue size:  8
[10:41:30][I][script.watchdog:3119]: Nextion:
[10:41:30][I][script.watchdog:3120]:   Queue size:  2
[10:41:30][I][script.watchdog:3122]:   Is setup:    True
[10:41:30][I][script.watchdog:3129]:   Init:        True
[10:41:30][I][script.watchdog:3137]:   TFT:         4.2dev.4
[10:41:30][W][component:214]: Component time took a long time for an operation (0.11 s).
[10:41:30][W][component:215]: Components should block for at most 20-30ms.

```


> Also, is this the embedded climate (add-on) or are you using some other climate entity from Home Assistant?

climate control comes from Thermia Genesis integration, not the embedded add-on.

**Comment by edwardtfn** [comment]
Ok, thanks for sharing. I've to study all this data now and understand why it is failing.
I come back to you soon.

By the way, I see you are using 921600 bps. As this can cause issues in some more populated pages (specially the button pages), I would suggest you to set it back to 115200 bps. With this version on `dev`, it should always try the TFT upload at 921600 bps as default (set by substitution: `upload_tft_baud_rate: "921600"`), so you should be good with the file transfer.

**Comment by edwardtfn** [comment]
Could you please update your blueprint and try it again?

**Comment by Floppe** [comment]
![IMG_20240104_120717](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/238729/e6cd92d8-4ccc-4eb8-aa2b-039e89a9d62a)

It became dual state now. Also wrong min/max, but otherwise it works.
Same warnings in ESP home though.

**Comment by edwardtfn** [comment]
It shouldn't be dual, but for some reason we cannot detect if it is `heat` or `cool`, which was not a problem before, with a single slider, but it is now when 2 sliders are available, one for `target_temp_low` and another one for `target_temp_high` (which is the 18C and 19C shown in your screen - an error, as only 19C should be shown).
Min/Max defines the limits of the slider, not the values shown.

Working on this...

**Comment by edwardtfn** [comment]
Could you please upgrade your system to v4.2dev.5 and try it again. All the 3 parts (TFT, ESPHome and Blueprint) must be updated. 😞 
I couldn't try myself, will try it tomorrow, but it would be nice if you can play with the system a bit and give some feedback (and logs, in case of errors).
