### ISSUE TITLE
`BUG` Problem while open climate page of local thermostat

### ISSUE THREAD

**Issue by DerT94** [Blackymas/NSPanel_HA_Blueprint#1613]
### TFT Version

4.2.1

### ESPHome Version

4.2.1

### Blueprint Version

4.2.1

### Panel Model

NSPanel EU Model

### What is the bug?

No control is displayed when opening the climate page. The error occurs since version 4.2.1 and only with the local thermostat

### Steps to Reproduce

I have two NSPanels and have configured them identically.
Both show the same behaviour.

1. Install an NSPanel with Climate Addon (Heater)
2. Configure the Blueprint for the own Thermostat
3. Open the Climate page

Below two pictures

The NSPanel his own Thermostat in the blueprint
![24-01-12 17-28-37 4236](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/58786605/eb677f69-1652-4a7d-8f2c-c7c2562aa125)

Another NSPanel with the thermostat from the fist one in the blueprint
![24-01-12 17-28-28 4235](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/58786605/d046b0cf-770d-4e0d-9669-66cc2903f3d1)

### Your panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel-buero" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  heater_relay: "1"     # Possible values: "1" or "2"
  temp_units: "°C"      # Temperatures in Fahrenheit
  temp_min: "16"        # Min supported temperature is 40°F
  temp_max: "26"        # Max supported temperature is 80°F
  temp_step: "1"        # Temperature granularity is 1°F
  heat_deadband: "1.2"  # Temperature delta before engaging heat
  heat_overrun: "1.2"   # Temperature delta before disengaging heat

# Customization area
##### My customization - Start #####
wifi:
  networks:
    - id: !extend wifi_default
      hidden: true
  fast_connect: true

  # Encrypt the communication between ESPHome and Home Assistant
api:
  encryption:
    key: !secret api_encryption_key
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

### ESPHome logs

```logs
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/nspanel-white.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Starting log output from 10.30.1.39 using esphome API
INFO Successfully connected to nspanel-buero @ 10.30.1.39 in 0.024s
INFO Successful handshake with nspanel-buero @ 10.30.1.39 in 0.108s
[17:34:38][I][app:102]: ESPHome version 2023.12.5 compiled on Jan 12 2024, 17:12:59
[17:34:38][C][wifi:573]: WiFi:
[17:34:38][C][wifi:405]:   Local MAC: C0:49:EF:FA:27:70
[17:34:38][C][wifi:410]:   SSID: ''[redacted]
[17:34:38][C][wifi:411]:   IP Address: 10.30.1.39
[17:34:38][C][wifi:413]:   BSSID: [redacted]
[17:34:38][C][wifi:414]:   Hostname: 'nspanel-buero'
[17:34:38][C][wifi:416]:   Signal strength: -50 dB ▂▄▆█
[17:34:38][C][wifi:420]:   Channel: 1
[17:34:38][C][wifi:421]:   Subnet: 255.255.0.0
[17:34:38][C][wifi:422]:   Gateway: 10.30.0.1
[17:34:38][C][wifi:423]:   DNS1: 10.10.0.3
[17:34:38][C][wifi:424]:   DNS2: 0.0.0.0
[17:34:38][C][logger:443]: Logger:
[17:34:38][C][logger:444]:   Level: DEBUG
[17:34:38][C][logger:445]:   Log Baud Rate: 0
[17:34:38][C][logger:447]:   Hardware UART: UART0
[17:34:38][C][uart.idf:139]: UART Bus 0:
[17:34:38][C][uart.idf:140]:   TX Pin: GPIO16
[17:34:38][C][uart.idf:141]:   RX Pin: GPIO17
[17:34:38][C][uart.idf:143]:   RX Buffer Size: 256
[17:34:38][C][uart.idf:145]:   Baud Rate: 115200 baud
[17:34:38][C][uart.idf:146]:   Data Bits: 8
[17:34:38][C][uart.idf:147]:   Parity: NONE
[17:34:38][C][uart.idf:148]:   Stop bits: 1
[17:34:38][C][ledc.output:164]: LEDC Output:
[17:34:38][C][ledc.output:165]:   Pin GPIO21
[17:34:38][C][ledc.output:166]:   LEDC Channel: 0
[17:34:38][C][ledc.output:167]:   PWM Frequency: 1000.0 Hz
[17:34:38][C][ledc.output:168]:   Bit depth: 16
[17:34:38][C][template.binary_sensor:028]: Template Binary Sensor 'nspanel-buero Nextion display'
[17:34:38][C][template.binary_sensor:028]:   Device Class: 'connectivity'
[17:34:38][C][template.number:050]: Template Number 'nspanel-buero Display Brightness'
[17:34:38][C][template.number:050]:   Unit of Measurement: '%'
[17:34:38][C][template.number:051]:   Optimistic: YES
[17:34:38][C][template.number:052]:   Update Interval: 60.0s
[17:34:38][C][template.number:050]: Template Number 'nspanel-buero Display Brightness Dimdown'
[17:34:38][C][template.number:050]:   Unit of Measurement: '%'
[17:34:38][C][template.number:051]:   Optimistic: YES
[17:34:38][C][template.number:052]:   Update Interval: 60.0s
[17:34:38][C][template.number:050]: Template Number 'nspanel-buero Display Brightness Sleep'
[17:34:38][C][template.number:050]:   Unit of Measurement: '%'
[17:34:38][C][template.number:051]:   Optimistic: YES
[17:34:38][C][template.number:052]:   Update Interval: 60.0s
[17:34:38][C][template.number:050]: Template Number 'nspanel-buero Temperature Correction'
[17:34:38][C][template.number:050]:   Unit of Measurement: '°C'
[17:34:38][C][template.number:051]:   Optimistic: YES
[17:34:38][C][template.number:052]:   Update Interval: 60.0s
[17:34:38][C][template.number:050]: Template Number 'nspanel-buero Timeout Page'
[17:34:38][C][template.number:050]:   Icon: 'mdi:timer'
[17:34:38][C][template.number:050]:   Unit of Measurement: 's'
[17:34:38][C][template.number:051]:   Optimistic: YES
[17:34:38][C][template.number:052]:   Update Interval: 60.0s
[17:34:38][C][template.number:050]: Template Number 'nspanel-buero Timeout Dimming'
[17:34:38][C][template.number:050]:   Icon: 'mdi:timer'
[17:34:38][C][template.number:050]:   Unit of Measurement: 's'
[17:34:39][C][template.number:051]:   Optimistic: YES
[17:34:39][C][template.number:052]:   Update Interval: 60.0s
[17:34:39][C][template.number:050]: Template Number 'nspanel-buero Timeout Sleep'
[17:34:39][C][template.number:050]:   Icon: 'mdi:timer'
[17:34:39][C][template.number:050]:   Unit of Measurement: 's'
[17:34:39][C][template.number:051]:   Optimistic: YES
[17:34:39][C][template.number:052]:   Update Interval: 60.0s
[17:34:39][C][template.select:065]: Template Select 'nspanel-buero Baud rate'
[17:34:39][C][template.select:065]:   Icon: 'mdi:swap-horizontal'
[17:34:39][C][template.select:066]:   Update Interval: 60.0s
[17:34:39][C][template.select:069]:   Optimistic: YES
[17:34:39][C][template.select:070]:   Initial Option: 115200
[17:34:39][C][template.select:071]:   Restore Value: YES
[17:34:39][C][template.select:065]: Template Select 'nspanel-buero Wake-up page'
[17:34:39][C][template.select:065]:   Icon: 'mdi:page-next-outline'
[17:34:39][C][template.select:066]:   Update Interval: 60.0s
[17:34:39][C][template.select:069]:   Optimistic: YES
[17:34:39][C][template.select:070]:   Initial Option: home
[17:34:39][C][template.select:071]:   Restore Value: YES
[17:34:39][C][template.select:065]: Template Select 'nspanel-buero Update TFT display - Branch'
[17:34:39][C][template.select:065]:   Icon: 'mdi:file-sync'
[17:34:39][C][template.select:066]:   Update Interval: 60.0s
[17:34:39][C][template.select:069]:   Optimistic: YES
[17:34:39][C][template.select:070]:   Initial Option: main
[17:34:39][C][template.select:071]:   Restore Value: YES
[17:34:39][C][template.select:065]: Template Select 'nspanel-buero Update TFT display - Model'
[17:34:39][C][template.select:065]:   Icon: 'mdi:file-sync'
[17:34:39][C][template.select:066]:   Update Interval: 60.0s
[17:34:39][C][template.select:069]:   Optimistic: YES
[17:34:39][C][template.select:070]:   Initial Option: Use nextion_update_url
[17:34:39][C][template.select:071]:   Restore Value: YES
[17:34:39][C][template.text_sensor:020]: Template Sensor 'nspanel-buero Detailed Entity'
[17:34:39][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[17:34:39][C][template.text_sensor:020]: Template Sensor 'nspanel-buero Current page'
[17:34:39][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[17:34:39][C][template.text_sensor:020]: Template Sensor 'nspanel-buero Notification Label'
[17:34:39][C][template.text_sensor:020]: Template Sensor 'nspanel-buero Notification Text'
[17:34:39][C][switch.gpio:068]: GPIO Switch 'nspanel-buero Relay 1'
[17:34:39][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[17:34:39][C][switch.gpio:031]:   Pin: GPIO22
[17:34:39][C][switch.gpio:068]: GPIO Switch 'nspanel-buero Relay 2'
[17:34:39][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[17:34:39][C][switch.gpio:031]:   Pin: GPIO19
[17:34:39][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'nspanel-buero Left Button'
[17:34:39][C][gpio.binary_sensor:016]:   Pin: GPIO14
[17:34:39][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'nspanel-buero Right Button'
[17:34:39][C][gpio.binary_sensor:016]:   Pin: GPIO27
[17:34:39][C][switch.gpio:068]: GPIO Switch 'nspanel-buero Nextion display - Power'
[17:34:39][C][switch.gpio:091]:   Restore Mode: always ON
[17:34:39][C][switch.gpio:031]:   Pin: GPIO4
[17:34:40][C][template.switch:068]: Template Switch 'nspanel-buero Notification sound'
[17:34:40][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[17:34:40][C][template.switch:057]:   Optimistic: YES
[17:34:40][C][template.switch:068]: Template Switch 'nspanel-buero Relay 1 Local'
[17:34:40][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[17:34:40][C][template.switch:057]:   Optimistic: YES
[17:34:40][C][template.switch:068]: Template Switch 'nspanel-buero Relay 2 Local'
[17:34:40][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[17:34:40][C][template.switch:057]:   Optimistic: YES
[17:34:40][C][template.switch:068]: Template Switch 'nspanel-buero Relay 0 (dummy)'
[17:34:40][C][template.switch:091]:   Restore Mode: always OFF
[17:34:40][C][template.switch:057]:   Optimistic: YES
[17:34:40][C][template.switch:068]: Template Switch 'nspanel-buero Notification unread'
[17:34:40][C][template.switch:091]:   Restore Mode: always OFF
[17:34:40][C][template.switch:057]:   Optimistic: YES
[17:34:40][C][rtttl:029]: Rtttl
[17:34:40][C][nextion:128]: Nextion:
[17:34:40][C][nextion:129]:   Device Model:     NX4832F035_011C
[17:34:40][C][nextion:130]:   Firmware Version: 72
[17:34:40][C][nextion:131]:   Serial Number:    BD8C3401C1F90872
[17:34:40][C][nextion:132]:   Flash Size:       16777216
[17:34:40][C][nextion:133]:   Wake On Touch:    YES
[17:34:40][C][nextion:134]:   Exit reparse:     YES
[17:34:40][C][restart.button:017]: Restart Button 'nspanel-buero Restart'
[17:34:40][C][adc:097]: ADC Sensor 'ntc_source'
[17:34:40][C][adc:097]:   Device Class: 'voltage'
[17:34:40][C][adc:097]:   State Class: 'measurement'
[17:34:40][C][adc:097]:   Unit of Measurement: 'V'
[17:34:40][C][adc:097]:   Accuracy Decimals: 2
[17:34:40][C][adc:107]:   Pin: GPIO38
[17:34:40][C][adc:122]:  Attenuation: 11db
[17:34:40][C][adc:142]:   Update Interval: 60.0s
[17:34:40][C][resistance:010]: Resistance Sensor 'resistance_sensor'
[17:34:40][C][resistance:010]:   State Class: 'measurement'
[17:34:40][C][resistance:010]:   Unit of Measurement: 'Ω'
[17:34:40][C][resistance:010]:   Accuracy Decimals: 1
[17:34:40][C][resistance:010]:   Icon: 'mdi:flash'
[17:34:40][C][resistance:011]:   Configuration: DOWNSTREAM
[17:34:40][C][resistance:012]:   Resistor: 11200.00Ω
[17:34:40][C][resistance:013]:   Reference Voltage: 3.3V
[17:34:40][C][ntc:014]: NTC Sensor 'nspanel-buero Temperature'
[17:34:40][C][ntc:014]:   Device Class: 'temperature'
[17:34:40][C][ntc:014]:   State Class: 'measurement'
[17:34:40][C][ntc:014]:   Unit of Measurement: '°C'
[17:34:40][C][ntc:014]:   Accuracy Decimals: 1
[17:34:40][C][thermostat.climate:1290]: Thermostat 'nspanel-buero Thermostat'
[17:34:40][C][thermostat.climate:1295]:   Start-up Delay Enabled: NO
[17:34:40][C][thermostat.climate:1311]:   Heating Parameters:
[17:34:40][C][thermostat.climate:1312]:     Deadband: 1.2°C
[17:34:40][C][thermostat.climate:1313]:     Overrun: 1.2°C
[17:34:40][C][thermostat.climate:1320]:     Minimum Off Time: 300s
[17:34:40][C][thermostat.climate:1322]:     Minimum Run Time: 300s
[17:34:40][C][thermostat.climate:1337]:   Minimum Idle Time: 30s
[17:34:40][C][thermostat.climate:1338]:   Supports AUTO: NO
[17:34:40][C][thermostat.climate:1339]:   Supports HEAT/COOL: NO
[17:34:40][C][thermostat.climate:1340]:   Supports COOL: NO
[17:34:40][C][thermostat.climate:1341]:   Supports DRY: NO
[17:34:40][C][thermostat.climate:1342]:   Supports FAN_ONLY: NO
[17:34:40][C][thermostat.climate:1344]:   Supports FAN_ONLY_ACTION_USES_FAN_MODE_TIMER: NO
[17:34:40][C][thermostat.climate:1345]:   Supports FAN_ONLY_COOLING: NO
[17:34:40][C][thermostat.climate:1350]:   Supports FAN_WITH_HEATING: NO
[17:34:40][C][thermostat.climate:1352]:   Supports HEAT: YES
[17:34:40][C][thermostat.climate:1353]:   Supports FAN MODE ON: NO
[17:34:40][C][thermostat.climate:1354]:   Supports FAN MODE OFF: NO
[17:34:40][C][thermostat.climate:1355]:   Supports FAN MODE AUTO: NO
[17:34:40][C][thermostat.climate:1356]:   Supports FAN MODE LOW: NO
[17:34:40][C][thermostat.climate:980]:       HOME Default Mode: HEAT
[17:34:40][C][thermostat.climate:1377]:   Supported CUSTOM PRESETS: 
[17:34:40][C][thermostat.climate:1381]:     Supports Off: YES
[17:34:40][C][thermostat.climate:959]:       Off Is Default: YES
[17:34:40][C][thermostat.climate:966]:       Off Default Target Temperature Low: 18.0°C
[17:34:40][C][thermostat.climate:980]:       Off Default Mode: OFF
[17:34:40][C][thermostat.climate:1385]:   On boot, restore from: MEMORY
[17:34:41][C][homeassistant.time:010]: Home Assistant Time:
[17:34:41][C][homeassistant.time:011]:   Timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
[17:34:41][C][status:034]: Status Binary Sensor 'nspanel-buero Status'
[17:34:41][C][status:034]:   Device Class: 'connectivity'
[17:34:42][C][mdns:115]: mDNS:
[17:34:42][C][mdns:116]:   Hostname: nspanel-buero
[17:34:42][C][ota:097]: Over-The-Air Updates:
[17:34:42][C][ota:098]:   Address: nspanel-buero.local:3232
[17:34:42][C][ota:101]:   Using Password.
[17:34:42][C][api:139]: API Server:
[17:34:42][C][api:140]:   Address: nspanel-buero.local:6053
[17:34:42][C][api:142]:   Using noise encryption: YES
[17:34:42][C][wifi_signal.sensor:009]: WiFi Signal 'nspanel-buero RSSI'
[17:34:42][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[17:34:42][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[17:34:42][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[17:34:42][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[17:34:49][D][nextion:446]: Got touch event:
[17:34:49][D][nextion:447]:   page_id:      9
[17:34:49][D][nextion:448]:   component_id: 4
[17:34:49][D][nextion:449]:   event type:   PRESS
[17:34:49][D][nextion:464]: Got new page: 0
[17:34:49][D][display.disp1.on_page:714]: Nextion page changed
[17:34:49][D][display.disp1.on_page:715]: New page: home (0)
[17:34:49][D][text_sensor:064]: 'nspanel-buero Current page': Sending state 'home'
[17:34:49][D][text_sensor:064]: 'nspanel-buero Detailed Entity': Sending state ''
[17:34:49][D][script.page_changed:2108]: New page: home
[17:34:49][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[17:34:49][D][script.timer_dim:2923]: Waking up on page: home
[17:34:49][D][script.set_brightness:2496]: brightness: 24%
[17:34:50][D][sensor:094]: 'nspanel-buero Page Id': Sending state 0.00000  with 2 decimals of accuracy
[17:34:50][D][sensor.page_id:1368]: New page Id: 0
[17:34:51][D][nextion:446]: Got touch event:
[17:34:51][D][nextion:447]:   page_id:      0
[17:34:51][D][nextion:448]:   component_id: 4
[17:34:51][D][nextion:449]:   event type:   PRESS
[17:34:51][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[17:34:51][D][script.timer_dim:2923]: Waking up on page: home
[17:34:51][D][script.set_brightness:2496]: brightness: 24%
[17:34:51][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[17:34:51][D][nextion:446]: Got touch event:
[17:34:51][D][nextion:447]:   page_id:      0
[17:34:51][D][nextion:448]:   component_id: 4
[17:34:51][D][nextion:449]:   event type:   RELEASE
[17:34:51][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[17:34:51][D][script.timer_dim:2923]: Waking up on page: home
[17:34:51][D][script.set_brightness:2496]: brightness: 24%
[17:34:51][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[17:34:51][D][text_sensor:064]: 'nspanel-buero NSPanel local event': Sending state '{"page": "home", "component": "climate", "event": "click"}'
[17:34:51][D][text_sensor:064]: 'nspanel-buero Detailed Entity': Sending state 'embedded_climate'
[17:34:51][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "home", "component": "climate", "event": "click"}"
[17:34:51][D][nextion:464]: Got new page: 6
[17:34:51][D][display.disp1.on_page:714]: Nextion page changed
[17:34:51][D][display.disp1.on_page:715]: New page: climate (6)
[17:34:51][D][text_sensor:064]: 'nspanel-buero Current page': Sending state 'climate'
[17:34:51][D][script.page_changed:2108]: New page: climate
[17:34:51][D][script.page_changed:2109]: Entity shown: embedded_climate
[17:34:51][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[17:34:51][D][script.timer_dim:2923]: Waking up on page: climate
[17:34:51][D][script.set_brightness:2496]: brightness: 24%
[17:34:51][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[17:34:51][D][sensor:094]: 'nspanel-buero Page Id': Sending state 6.00000  with 2 decimals of accuracy
[17:34:51][D][sensor.page_id:1368]: New page Id: 6
[17:34:53][I][addon_upload_tft.script.report_settings:189]: TFT URL: https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft
[17:34:53][I][addon_upload_tft.script.report_settings:190]: Substitutions:
[17:34:53][I][addon_upload_tft.script.report_settings:191]:   nextion_update_url:        https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft
[17:34:53][I][addon_upload_tft.script.report_settings:192]:   nextion_update_base_url:   https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/
[17:34:53][I][addon_upload_tft.script.report_settings:193]:   upload_tft_chunk_size_max: 32768
[17:34:53][I][addon_upload_tft.script.report_settings:194]:   upload_tft_baud_rate:      921600
[17:35:06][D][script.timer_page:2908]: Fallback to page Home
[17:35:06][D][nextion:464]: Got new page: 0
[17:35:06][D][display.disp1.on_page:714]: Nextion page changed
[17:35:06][D][display.disp1.on_page:715]: New page: home (0)
[17:35:06][D][text_sensor:064]: 'nspanel-buero Current page': Sending state 'home'
[17:35:06][D][text_sensor:064]: 'nspanel-buero Detailed Entity': Sending state ''
[17:35:06][D][script.page_changed:2108]: New page: home
[17:35:06][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[17:35:06][D][script.timer_dim:2923]: Waking up on page: home
[17:35:06][D][script.set_brightness:2496]: brightness: 24%
[17:35:06][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[17:35:06][D][sensor:094]: 'nspanel-buero Page Id': Sending state 0.00000  with 2 decimals of accuracy
[17:35:06][D][sensor.page_id:1368]: New page Id: 0
[17:35:22][D][esp32.preferences:114]: Saving 1 preferences to flash...
[17:35:22][D][esp32.preferences:143]: Saving 1 preferences to flash: 1 cached, 0 written, 0 failed
[17:35:24][D][sensor:094]: 'ntc_source': Sending state 1.59100 V with 2 decimals of accuracy
[17:35:24][D][resistance:039]: 'resistance_sensor' - Resistance 10426.7Ω
[17:35:24][D][sensor:094]: 'resistance_sensor': Sending state 10426.68164 Ω with 1 decimals of accuracy
[17:35:24][D][ntc:026]: 'nspanel-buero Temperature' - Temperature: 24.1°C
[17:35:24][D][sensor:094]: 'nspanel-buero Temperature': Sending state 24.06264 °C with 1 decimals of accuracy
[17:35:24][D][climate:396]: 'nspanel-buero Thermostat' - Sending state:
[17:35:24][D][climate:399]:   Mode: HEAT
[17:35:24][D][climate:401]:   Action: HEATING
[17:35:24][D][climate:419]:   Current Temperature: 24.06°C
[17:35:24][D][climate:425]:   Target Temperature: 26.00°C
[17:35:24][D][addon_climate_base.climate.thermostat_embedded.on_state:055]: Starting
[17:35:24][D][addon_climate_base.climate.thermostat_embedded.on_state:058]: Finished
[17:35:30][I][script.watchdog:3103]: Wi-Fi:         Good (-50 dBm)
[17:35:30][I][script.watchdog:3123]: API:           Connected
[17:35:30][I][script.watchdog:3141]: Blueprint:     4.2.1
[17:35:30][I][script.watchdog:3154]: ESPHome:
[17:35:30][I][script.watchdog:3155]:   Version:     4.2.1
[17:35:30][I][script.watchdog:3160]:   Framework:   esp-idf
[17:35:30][I][script.watchdog:3164]: UART:
[17:35:30][I][script.watchdog:3165]:   Baud rate:   115200 bps
[17:35:30][I][script.watchdog:3166]:   Queue size:  8
[17:35:30][I][script.watchdog:3170]: Nextion:
[17:35:30][I][script.watchdog:3171]:   Queue size:  2
[17:35:30][I][script.watchdog:3173]:   Is setup:    True
[17:35:30][I][script.watchdog:3180]:   Init:        True
[17:35:30][I][script.watchdog:3188]:   TFT:         4.2.1
[17:35:30][I][addon_climate_base.script.watchdog:183]: Add-on climate:
[17:35:30][I][addon_climate_base.script.watchdog:192]:   Heat:  Enabled
[17:35:30][I][addon_climate_base.script.watchdog:194]:   Relay: 1
[17:35:32][D][sensor:094]: 'nspanel-buero RSSI': Sending state -50.00000 dBm with 0 decimals of accuracy
[17:35:36][D][script.set_brightness:2496]: brightness: 24%
```

### Home Assistant logs

```logs
2024-01-12 17:37:53.581 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] NSPanel - Buero: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:37:53.582 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] NSPanel - Buero: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: Error executing script. Error rendering template for if at pos 4: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:37:53.582 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] NSPanel - Buero: Main choices: NSPanel event: Choose at step 2: Page changed: Error executing script. Error rendering template for choose at pos 1: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:37:53.583 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] NSPanel - Buero: Main choices: NSPanel event: Error executing script. Error rendering template for choose at pos 2: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:37:53.583 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] NSPanel - Buero: Error executing script. Error rendering template for choose at pos 2: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:37:53.584 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] Error while executing automation automation.nspanel_buero: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:38:09.892 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] NSPanel - Buero: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:38:09.892 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] NSPanel - Buero: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: Error executing script. Error rendering template for if at pos 4: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:38:09.892 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] NSPanel - Buero: Main choices: NSPanel event: Choose at step 2: Page changed: Error executing script. Error rendering template for choose at pos 1: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:38:09.892 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] NSPanel - Buero: Main choices: NSPanel event: Error executing script. Error rendering template for choose at pos 2: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:38:09.892 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] NSPanel - Buero: Error executing script. Error rendering template for choose at pos 2: AttributeError: 'list' object has no attribute 'lower'
2024-01-12 17:38:09.893 ERROR (MainThread) [homeassistant.components.automation.nspanel_buero] Error while executing automation automation.nspanel_buero: AttributeError: 'list' object has no attribute 'lower'
```

**Comment by sheaur** [comment]
Same problem

**Comment by neuhausf** [comment]
Same here.

**Comment by DerT94** [comment]
Rollback to V4.1.4 works great

**Comment by sheaur** [comment]
I downgrade to 4.1.4 version too

**Comment by nikdom** [comment]
same here. 
also it seems that the values of the temperature sensor in the nspanel are way higher than before, or the panel heats up more. not sure whether this is related. (og_sz_temp_hum is an aqara temperature sensor to compare; og_sz_nspanel is the panel)
![IMG_5192](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/5239330/3dc4e3d6-2d06-4ea8-9467-16bc7ca09c68)

**Comment by MichaelHeimann** [comment]
Same here. BUT: It does complete loading after an eternity of about 30 to 60 seconds (touch the screen from time to time to avoid timeout return to homescreen).

Tried the delay to avoid synchronization parameter (even at max, 100) but didn't make any difference.

**Comment by Eisenhauer1987** [comment]
same problem with 4.2.1 here. No control is displayed when opening the climate page. After a long time or if I try to set a temperature in the empty bar, the values showing up.

**Comment by edwardtfn** [comment]
The problem is that page is not constructing when opening. It is constructing when the data changes.
I'm working on that.

**Comment by edwardtfn** [comment]
I believe this issue is fixed in `dev` and will be included in the patch v4.2.2 to be released soon.

**Comment by phendrickx** [comment]
Can it be that in release 4.3.11 the issue is still present? Have the same issue that nothing appears on the climate page.

**Comment by MichaelHeimann** [comment]
> Can it be that in release 4.3.11 the issue is still present? Have the same issue that nothing appears on the climate page.

I'm on 4.3.11 and just checked on three panels - all fine.
Do you have a log of the panel?

**Comment by phendrickx** [comment]
Here config inside esp:
`substitutions:
  # Settings - Editable values
  device_name: "nspanel-thermostate-home"
  friendly_name: "nspanel-thermostate-home"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://xxx.xxx.xxx.xxx/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"
  ##### addon-configuration #####
  ## addon_climate ##
  heater_relay: "1" #Use relay 1
  temp_min: "15" 
  temp_max: "25" 
  temp_step: "0.5"
 ##### CHANGE ME END #####
climate:
  - id: !extend thermostat_embedded
    visual:
      temperature_step: ${temp_step}
    preset:
      - name: Verwarming
        default_target_temperature_low: 18.3
        mode: "heat"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml`


The logs:
`INFO ESPHome 2024.8.3
INFO Reading configuration /config/esphome/nspanel-thermostate-home.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
WARNING Found 'xxxxxxxxxx' (see substitutions->wifi_password) which looks like a substitution, but 'xxx' was not declared
WARNING Found 'xxxxxxxxxx' (see substitutions->ota_password) which looks like a substitution, but 'xxx' was not declared
WARNING Found 'xxxxxxxxxx' (see substitutions->wifi_password) which looks like a substitution, but 'xxx' was not declared
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@v4.3.11
INFO Detected timezone 'Europe/Brussels'
INFO Starting log output from 192.168.30.23 using esphome API
INFO Successfully connected to nspanel-thermostate-home @ 192.168.30.23 in 0.049s
INFO Successful handshake with nspanel-thermostate-home @ 192.168.30.23 in 0.023s
[12:48:51][I][app:100]: ESPHome version 2024.8.3 compiled on Sep  9 2024, 22:11:53
[12:48:51][I][app:102]: Project esphome.NSPanel_HA_Blueprint version 4.3.11
[12:48:51][C][wifi:600]: WiFi:
[12:48:51][C][wifi:428]:   Local MAC: 80:64:6F:C4:D8:70
[12:48:51][C][wifi:433]:   SSID: 'Home18_10'[redacted]
[12:48:51][C][wifi:436]:   IP Address: 192.168.30.23
[12:48:51][C][wifi:440]:   BSSID: B6:FB:E4:BF:2C:A5[redacted]
[12:48:51][C][wifi:441]:   Hostname: 'nspanel-thermostate-home'
[12:48:51][C][wifi:443]:   Signal strength: -75 dB ▂▄▆█
[12:48:51][C][wifi:447]:   Channel: 1
[12:48:51][C][wifi:448]:   Subnet: 255.255.255.0
[12:48:51][C][wifi:449]:   Gateway: 192.168.30.254
[12:48:51][C][wifi:450]:   DNS1: 192.168.123.2
[12:48:51][C][wifi:451]:   DNS2: 192.168.123.1
[12:48:51][C][logger:185]: Logger:
[12:48:51][C][logger:186]:   Level: DEBUG
[12:48:51][C][logger:188]:   Log Baud Rate: 0
[12:48:51][C][logger:189]:   Hardware UART: UART0
[12:48:51][C][uart.idf:159]: UART Bus 0:
[12:48:51][C][uart.idf:160]:   TX Pin: GPIO16
[12:48:51][C][uart.idf:161]:   RX Pin: GPIO17
[12:48:51][C][uart.idf:163]:   RX Buffer Size: 256
[12:48:51][C][uart.idf:165]:   Baud Rate: 115200 baud
[12:48:51][C][uart.idf:166]:   Data Bits: 8
[12:48:51][C][uart.idf:167]:   Parity: NONE
[12:48:51][C][uart.idf:168]:   Stop bits: 1
[12:48:51][C][ledc.output:176]: LEDC Output:
[12:48:51][C][ledc.output:177]:   Pin GPIO21
[12:48:51][C][ledc.output:178]:   LEDC Channel: 0
[12:48:51][C][ledc.output:179]:   PWM Frequency: 1000.0 Hz
[12:48:51][C][ledc.output:180]:   Phase angle: 0.0°
[12:48:51][C][ledc.output:181]:   Bit depth: 16
[12:48:52][C][template.binary_sensor:028]: Template Binary Sensor 'Nextion display'
[12:48:52][C][template.binary_sensor:028]:   Device Class: 'connectivity'
[12:48:52][C][template.number:050]: Template Number 'Display Brightness'
[12:48:52][C][template.number:050]:   Unit of Measurement: '%'
[12:48:52][C][template.number:051]:   Optimistic: YES
[12:48:52][C][template.number:052]:   Update Interval: 60.0s
[12:48:52][C][template.number:050]: Template Number 'Display Brightness Dimdown'
[12:48:52][C][template.number:050]:   Unit of Measurement: '%'
[12:48:52][C][template.number:051]:   Optimistic: YES
[12:48:52][C][template.number:052]:   Update Interval: 60.0s
[12:48:52][C][template.number:050]: Template Number 'Display Brightness Sleep'
[12:48:52][C][template.number:050]:   Unit of Measurement: '%'
[12:48:52][C][template.number:051]:   Optimistic: YES
[12:48:52][C][template.number:052]:   Update Interval: 60.0s
[12:48:52][C][template.number:050]: Template Number 'Temperature Correction'
[12:48:53][C][template.number:050]:   Unit of Measurement: '°C'
[12:48:53][C][mdns:116]: mDNS:
[12:48:53][C][mdns:117]:   Hostname: nspanel-thermostate-home
[12:48:53][C][esphome.ota:073]: Over-The-Air updates:
[12:48:53][C][esphome.ota:074]:   Address: nspanel-thermostate-home.local:3232
[12:48:53][C][esphome.ota:075]:   Version: 2
[12:48:53][C][esphome.ota:078]:   Password configured
[12:48:53][C][safe_mode:018]: Safe Mode:
[12:48:53][C][safe_mode:020]:   Boot considered successful after 60 seconds
[12:48:53][C][safe_mode:021]:   Invoke after 3 boot attempts
[12:48:53][C][safe_mode:023]:   Remain in safe mode for 180 seconds
[12:48:53][C][api:139]: API Server:
[12:48:53][C][api:140]:   Address: nspanel-thermostate-home.local:6053
[12:48:53][C][api:144]:   Using noise encryption: NO
[12:48:53][C][wifi_signal.sensor:010]: WiFi Signal 'RSSI'
[12:48:53][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[12:48:53][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[12:48:53][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[12:48:53][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[12:48:53][C][wifi_signal.sensor:010]:   Icon: 'mdi:wifi'
[12:48:58][D][sensor:094]: 'ntc_source': Sending state 1.75050 V with 2 decimals of accuracy
[12:48:58][D][resistance:039]: 'resistance_sensor' - Resistance 12652.9Ω
[12:48:58][D][sensor:094]: 'resistance_sensor': Sending state 12652.85742 Ω with 1 decimals of accuracy
[12:48:58][D][ntc:026]: 'Temperature' - Temperature: 19.8°C
[12:48:58][D][sensor:094]: 'Temperature': Sending state 19.79710 °C with 1 decimals of accuracy
[12:48:58][D][climate:396]: 'Thermostat' - Sending state:
[12:48:58][D][climate:399]:   Mode: HEAT
[12:48:58][D][climate:401]:   Action: OFF
[12:48:58][D][climate:419]:   Current Temperature: 19.80°C
[12:48:58][D][climate:425]:   Target Temperature: 20.00°C
[12:48:58][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:48:58][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_font_color"
[12:48:58][D][nextion:781]: Removing old queue type "NO_RESULT" name "send_command_printf"
[12:48:58][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:48:58][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_font_color"
[12:48:58][D][nextion:781]: Removing old queue type "NO_RESULT" name "send_command_printf"
[12:48:58][D][nextion:781]: Removing old queue type "NO_RESULT" name "send_command_printf"
[12:49:00][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:49:00][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_font_color"
[12:49:00][D][nextion:781]: Removing old queue type "NO_RESULT" name "send_command_printf"
[12:49:00][D][nextion:781]: Removing old queue type "NO_RESULT" name "send_command_printf"
[12:49:00][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_font_color"
[12:49:00][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:49:00][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:49:00][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:49:01][W][nspanel_ha_blueprint:2225]: Wi-Fi:         Weak (-72 dBm)
[12:49:01][C][nspanel_ha_blueprint:2235]: API:           Connected
[12:49:01][C][nspanel_ha_blueprint:2243]: Blueprint:
[12:49:01][C][nspanel_ha_blueprint:2245]:   Version:     4.3.11
[12:49:01][C][nspanel_ha_blueprint:2246]:   Init steps:  62 (100.0%)
[12:49:01][C][nspanel_ha_blueprint:2255]: ESPHome:
[12:49:01][C][nspanel_ha_blueprint:2256]:   Version:     4.3.11
[12:49:01][C][nspanel_ha_blueprint:2257]:   Compiler:    2024.8.3
[12:49:01][C][nspanel_ha_blueprint:2262]:   Framework:   ESP-IDF
[12:49:01][C][nspanel_ha_blueprint:2267]:   Free heap:
[12:49:01][C][nspanel_ha_blueprint:2271]:     Internal:   201196 bytes (57.2%)
[12:49:01][C][nspanel_ha_blueprint:2281]:     PSRAM:     2018151 bytes (96.8%)
[12:49:01][C][nspanel_ha_blueprint:2288]: UART:
[12:49:01][C][nspanel_ha_blueprint:2289]:   Baud rate:   115200 bps
[12:49:01][C][nspanel_ha_blueprint:2290]:   Queue size:  0
[12:49:01][C][nspanel_ha_blueprint:2294]: Nextion:
[12:49:01][C][nspanel_ha_blueprint:2295]:   Queue size:  12
[12:49:01][C][nspanel_ha_blueprint:2297]:   Is setup:    True
[12:49:01][C][nspanel_ha_blueprint:2304]:   Init:        True
[12:49:01][C][nspanel_ha_blueprint:2310]:   TFT:         4.3.11
[12:49:01][C][nspanel_ha_blueprint:2311]: Packages:
[12:49:01][C][nspanel_ha_blueprint:2313]:   - Core
[12:49:01][C][nspanel_ha_blueprint:2322]:   - Upload TFT
[12:49:01][C][nspanel_ha_blueprint:2325]:   - Climate - Base
[12:49:01][C][nspanel_ha_blueprint:2334]:   - Climate - Heat
[12:49:01][C][nspanel_ha_blueprint:097]: Add-on Upload TFT:
[12:49:01][C][nspanel_ha_blueprint:098]:   File model: NSPanel EU
[12:49:01][C][nspanel_ha_blueprint:099]:   Valid TFT:  YES
[12:49:01][C][nspanel_ha_blueprint:133]: Add-on climate:
[12:49:01][C][nspanel_ha_blueprint:142]:   Heat:  Enabled
[12:49:01][C][nspanel_ha_blueprint:144]:   Relay: 1
[12:49:01][W][component:237]: Component script took a long time for an operation (56 ms).
[12:49:01][W][component:238]: Components should block for at most 30 ms.
[12:49:02][D][climate:396]: 'Thermostat' - Sending state:
[12:49:02][D][climate:399]:   Mode: HEAT
[12:49:02][D][climate:401]:   Action: IDLE
[12:49:02][D][climate:419]:   Current Temperature: 19.80°C
[12:49:02][D][climate:425]:   Target Temperature: 20.00°C
[12:49:08][D][sensor:094]: 'ntc_source': Sending state 1.75080 V with 2 decimals of accuracy
[12:49:08][D][resistance:039]: 'resistance_sensor' - Resistance 12657.5Ω
[12:49:08][D][sensor:094]: 'resistance_sensor': Sending state 12657.47656 Ω with 1 decimals of accuracy
[12:49:08][D][ntc:026]: 'Temperature' - Temperature: 19.8°C
[12:49:08][D][sensor:094]: 'Temperature': Sending state 19.78917 °C with 1 decimals of accuracy
[12:49:08][D][climate:396]: 'Thermostat' - Sending state:
[12:49:08][D][climate:399]:   Mode: HEAT
[12:49:08][D][climate:401]:   Action: IDLE
[12:49:08][D][climate:419]:   Current Temperature: 19.79°C
[12:49:08][D][climate:425]:   Target Temperature: 20.00°C
[12:49:14][D][esp32.preferences:114]: Saving 1 preferences to flash...
[12:49:14][D][esp32.preferences:143]: Saving 1 preferences to flash: 1 cached, 0 written, 0 failed
[12:49:18][D][sensor:094]: 'ntc_source': Sending state 1.75117 V with 2 decimals of accuracy
[12:49:18][D][resistance:039]: 'resistance_sensor' - Resistance 12663.1Ω
[12:49:18][D][sensor:094]: 'resistance_sensor': Sending state 12663.12598 Ω with 1 decimals of accuracy
[12:49:18][D][ntc:026]: 'Temperature' - Temperature: 19.8°C
[12:49:18][D][sensor:094]: 'Temperature': Sending state 19.77948 °C with 1 decimals of accuracy
[12:49:18][D][climate:396]: 'Thermostat' - Sending state:
[12:49:18][D][climate:399]:   Mode: HEAT
[12:49:18][D][climate:401]:   Action: IDLE
[12:49:18][D][climate:419]:   Current Temperature: 19.78°C
[12:49:18][D][climate:425]:   Target Temperature: 20.00°C
[12:49:18][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_font_color"
[12:49:18][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:49:18][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:49:18][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:49:18][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:49:18][D][nextion:781]: Removing old queue type "NO_RESULT" name "send_command_printf"
[12:49:18][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_font_color"
[12:49:18][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:49:20][E][nextion:561]: ERROR: Received numeric return but next in queue "send_command_printf" is not a valid sensor type 0
[12:49:20][D][text_sensor:064]: 'Device Name': Sending state 'nspanel_thermostate_home'
[12:49:28][D][sensor:094]: 'ntc_source': Sending state 1.75233 V with 2 decimals of accuracy
[12:49:28][D][resistance:039]: 'resistance_sensor' - Resistance 12681.1Ω
[12:49:28][D][sensor:094]: 'resistance_sensor': Sending state 12681.11133 Ω with 1 decimals of accuracy
[12:49:28][D][ntc:026]: 'Temperature' - Temperature: 19.7°C
[12:49:28][D][sensor:094]: 'Temperature': Sending state 19.74865 °C with 1 decimals of accuracy
[12:49:28][D][climate:396]: 'Thermostat' - Sending state:
[12:49:28][D][climate:399]:   Mode: HEAT
[12:49:28][D][climate:401]:   Action: IDLE
[12:49:28][D][climate:419]:   Current Temperature: 19.75°C
[12:49:28][D][climate:425]:   Target Temperature: 20.00°C
[12:49:32][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[12:49:32][D][esp32.preferences:114]: Saving 2 preferences to flash...
[12:49:32][D][esp32.preferences:143]: Saving 2 preferences to flash: 1 cached, 1 written, 0 failed
[12:49:35][D][sensor:094]: 'RSSI': Sending state -79.00000 dBm with 0 decimals of accuracy
[12:49:38][D][sensor:094]: 'ntc_source': Sending state 1.75233 V with 2 decimals of accuracy
[12:49:38][D][resistance:039]: 'resistance_sensor' - Resistance 12681.1Ω
[12:49:38][D][sensor:094]: 'resistance_sensor': Sending state 12681.11133 Ω with 1 decimals of accuracy
[12:49:38][D][ntc:026]: 'Temperature' - Temperature: 19.7°C
[12:49:38][D][sensor:094]: 'Temperature': Sending state 19.74865 °C with 1 decimals of accuracy
[12:49:38][D][climate:396]: 'Thermostat' - Sending state:
[12:49:38][D][climate:399]:   Mode: HEAT
[12:49:38][D][climate:401]:   Action: IDLE
[12:49:38][D][climate:419]:   Current Temperature: 19.75°C
[12:49:38][D][climate:425]:   Target Temperature: 20.00°C
[12:49:44][D][nextion:457]: Got touch event:
[12:49:44][D][nextion:458]:   page_id:      1
[12:49:44][D][nextion:459]:   component_id: 4
[12:49:44][D][nextion:460]:   event type:   PRESS
[12:49:44][D][nextion:457]: Got touch event:
[12:49:44][D][nextion:458]:   page_id:      1
[12:49:44][D][nextion:459]:   component_id: 4
[12:49:44][D][nextion:460]:   event type:   RELEASE
[12:49:44][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[12:49:44][D][text_sensor:064]: 'NSPanel local event': Sending state '{"page": "home", "event": "short_click", "component": "indr_temp"}'
[12:49:44][D][text_sensor:064]: 'Detailed Entity': Sending state ''
[12:49:44][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "home", "event": "short_click", "component": "indr_temp"}"
[12:49:44][D][text_sensor:064]: 'Current Page': Sending state 'climate'
[12:49:44][D][script.page_changed:2644]: New page: climate
[12:49:44][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[12:49:44][D][nextion_textsensor:014]: Processed text_sensor "current_page" state "climate"
[12:49:46][D][nextion:457]: Got touch event:
[12:49:46][D][nextion:458]:   page_id:      7
[12:49:46][D][nextion:459]:   component_id: 4
[12:49:46][D][nextion:460]:   event type:   PRESS
[12:49:46][D][script:077]: Script 'timer_page' restarting (mode: restart)
[12:49:46][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[12:49:46][D][nextion:457]: Got touch event:
[12:49:46][D][nextion:458]:   page_id:      7
[12:49:46][D][nextion:459]:   component_id: 4
[12:49:46][D][nextion:460]:   event type:   RELEASE
[12:49:46][D][script:077]: Script 'timer_page' restarting (mode: restart)
[12:49:46][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[12:49:47][D][text_sensor:064]: 'NSPanel local event': Sending state '{"page": "climate", "key": "target_temp_high", "value": 0, "embedded": 0}'
[12:49:47][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "climate", "key": "target_temp_high", "value": 0, "embedded": 0}"
[12:49:47][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_font_color"
[12:49:47][D][nextion:781]: Removing old queue type "NO_RESULT" name "set_component_text"
[12:49:48][D][sensor:094]: 'ntc_source': Sending state 1.75233 V with 2 decimals of accuracy
[12:49:48][D][resistance:039]: 'resistance_sensor' - Resistance 12681.1Ω
[12:49:48][D][sensor:094]: 'resistance_sensor': Sending state 12681.11133 Ω with 1 decimals of accuracy
[12:49:48][D][ntc:026]: 'Temperature' - Temperature: 19.7°C
[12:49:48][D][sensor:094]: 'Temperature': Sending state 19.74865 °C with 1 decimals of accuracy
[12:49:48][D][climate:396]: 'Thermostat' - Sending state:
[12:49:48][D][climate:399]:   Mode: HEAT
[12:49:48][D][climate:401]:   Action: IDLE
[12:49:48][D][climate:419]:   Current Temperature: 19.75°C
[12:49:48][D][climate:425]:   Target Temperature: 20.00°C
[12:49:58][D][sensor:094]: 'ntc_source': Sending state 1.75267 V with 2 decimals of accuracy
[12:49:58][D][resistance:039]: 'resistance_sensor' - Resistance 12686.3Ω
[12:49:58][D][sensor:094]: 'resistance_sensor': Sending state 12686.25879 Ω with 1 decimals of accuracy
[12:49:58][D][ntc:026]: 'Temperature' - Temperature: 19.7°C
[12:49:58][D][sensor:094]: 'Temperature': Sending state 19.73983 °C with 1 decimals of accuracy
[12:49:58][D][climate:396]: 'Thermostat' - Sending state:
[12:49:58][D][climate:399]:   Mode: HEAT
[12:49:58][D][climate:401]:   Action: IDLE
[12:49:58][D][climate:419]:   Current Temperature: 19.74°C
[12:49:58][D][climate:425]:   Target Temperature: 20.00°C
[12:50:01][D][nextion:457]: Got touch event:
[12:50:01][D][nextion:458]:   page_id:      7
[12:50:01][D][nextion:459]:   component_id: 37
[12:50:01][D][nextion:460]:   event type:   PRESS
[12:50:01][D][script:077]: Script 'timer_page' restarting (mode: restart)
[12:50:01][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[12:50:01][D][text_sensor:064]: 'Current Page': Sending state 'home'
[12:50:01][D][script.page_changed:2644]: New page: home
[12:50:01][D][text_sensor:064]: 'Detailed Entity': Sending state ''
[12:50:01][D][script:077]: Script 'timer_page' restarting (mode: restart)
[12:50:01][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[12:50:01][D][nextion_textsensor:014]: Processed text_sensor "current_page" state "home"
[12:50:08][D][sensor:094]: 'ntc_source': Sending state 1.75283 V with 2 decimals of accuracy
[12:50:08][D][resistance:039]: 'resistance_sensor' - Resistance 12688.8Ω
[12:50:08][D][sensor:094]: 'resistance_sensor': Sending state 12688.83105 Ω with 1 decimals of accuracy
[12:50:08][D][ntc:026]: 'Temperature' - Temperature: 19.7°C
[12:50:08][D][sensor:094]: 'Temperature': Sending state 19.73543 °C with 1 decimals of accuracy
[12:50:08][D][climate:396]: 'Thermostat' - Sending state:
[12:50:08][D][climate:399]:   Mode: HEAT
[12:50:08][D][climate:401]:   Action: IDLE
[12:50:08][D][climate:419]:   Current Temperature: 19.74°C
[12:50:08][D][climate:425]:   Target Temperature: 20.00°C
[12:50:14][D][esp32.preferences:114]: Saving 1 preferences to flash...
[12:50:14][D][esp32.preferences:143]: Saving 1 preferences to flash: 1 cached, 0 written, 0 failed
[12:50:15][W][nspanel_ha_blueprint:2225]: Wi-Fi:         Weak (-79 dBm)
[12:50:15][C][nspanel_ha_blueprint:2235]: API:           Connected
[12:50:15][C][nspanel_ha_blueprint:2243]: Blueprint:
[12:50:15][C][nspanel_ha_blueprint:2245]:   Version:     4.3.11
[12:50:15][C][nspanel_ha_blueprint:2246]:   Init steps:  62 (100.0%)
[12:50:15][C][nspanel_ha_blueprint:2255]: ESPHome:
[12:50:15][C][nspanel_ha_blueprint:2256]:   Version:     4.3.11
[12:50:15][C][nspanel_ha_blueprint:2257]:   Compiler:    2024.8.3
[12:50:15][C][nspanel_ha_blueprint:2262]:   Framework:   ESP-IDF
[12:50:15][C][nspanel_ha_blueprint:2267]:   Free heap:
[12:50:15][C][nspanel_ha_blueprint:2271]:     Internal:   201944 bytes (57.5%)
[12:50:15][C][nspanel_ha_blueprint:2281]:     PSRAM:     2010411 bytes (96.4%)
[12:50:15][C][nspanel_ha_blueprint:2288]: UART:
[12:50:15][C][nspanel_ha_blueprint:2289]:   Baud rate:   115200 bps
[12:50:15][C][nspanel_ha_blueprint:2290]:   Queue size:  0
[12:50:15][C][nspanel_ha_blueprint:2294]: Nextion:
[12:50:15][C][nspanel_ha_blueprint:2295]:   Queue size:  2
[12:50:15][C][nspanel_ha_blueprint:2297]:   Is setup:    True
[12:50:15][C][nspanel_ha_blueprint:2304]:   Init:        True
[12:50:15][C][nspanel_ha_blueprint:2310]:   TFT:         4.3.11
[12:50:15][C][nspanel_ha_blueprint:2311]: Packages:
[12:50:15][C][nspanel_ha_blueprint:2313]:   - Core
[12:50:15][C][nspanel_ha_blueprint:2322]:   - Upload TFT
[12:50:15][C][nspanel_ha_blueprint:2325]:   - Climate - Base
[12:50:15][C][nspanel_ha_blueprint:2334]:   - Climate - Heat
[12:50:15][C][nspanel_ha_blueprint:097]: Add-on Upload TFT:
[12:50:15][C][nspanel_ha_blueprint:098]:   File model: NSPanel EU
[12:50:15][C][nspanel_ha_blueprint:099]:   Valid TFT:  YES
[12:50:15][C][nspanel_ha_blueprint:133]: Add-on climate:
[12:50:15][C][nspanel_ha_blueprint:142]:   Heat:  Enabled
[12:50:15][C][nspanel_ha_blueprint:144]:   Relay: 1
[12:50:15][W][component:237]: Component script took a long time for an operation (57 ms).
[12:50:15][W][component:238]: Components should block for at most 30 ms.
[12:50:18][D][sensor:094]: 'ntc_source': Sending state 1.75283 V with 2 decimals of accuracy
[12:50:18][D][resistance:039]: 'resistance_sensor' - Resistance 12688.8Ω
[12:50:18][D][sensor:094]: 'resistance_sensor': Sending state 12688.83105 Ω with 1 decimals of accuracy
[12:50:18][D][ntc:026]: 'Temperature' - Temperature: 19.7°C
[12:50:18][D][sensor:094]: 'Temperature': Sending state 19.73543 °C with 1 decimals of accuracy
[12:50:18][D][climate:396]: 'Thermostat' - Sending state:
[12:50:18][D][climate:399]:   Mode: HEAT
[12:50:18][D][climate:401]:   Action: IDLE
[12:50:18][D][climate:419]:   Current Temperature: 19.74°C
[12:50:18][D][climate:425]:   Target Temperature: 20.00°C
[12:50:20][D][text_sensor:064]: 'Device Name': Sending state 'nspanel_thermostate_home'
[12:50:22][D][nextion:457]: Got touch event:
[12:50:22][D][nextion:458]:   page_id:      1
[12:50:22][D][nextion:459]:   component_id: 4
[12:50:22][D][nextion:460]:   event type:   PRESS
[12:50:22][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[12:50:22][D][nextion:457]: Got touch event:
[12:50:22][D][nextion:458]:   page_id:      1
[12:50:22][D][nextion:459]:   component_id: 4
[12:50:22][D][nextion:460]:   event type:   RELEASE
[12:50:22][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[12:50:22][D][text_sensor:064]: 'NSPanel local event': Sending state '{"page": "home", "event": "short_click", "component": "indr_temp"}'
[12:50:22][D][text_sensor:064]: 'Detailed Entity': Sending state ''
[12:50:22][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "home", "event": "short_click", "component": "indr_temp"}"
[12:50:22][D][text_sensor:064]: 'Current Page': Sending state 'climate'
[12:50:22][D][script.page_changed:2644]: New page: climate
[12:50:22][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[12:50:22][D][nextion_textsensor:014]: Processed text_sensor "current_page" state "climate"
[12:50:28][D][sensor:094]: 'ntc_source': Sending state 1.75300 V with 2 decimals of accuracy
[12:50:28][D][resistance:039]: 'resistance_sensor' - Resistance 12691.4Ω
[12:50:28][D][sensor:094]: 'resistance_sensor': Sending state 12691.40527 Ω with 1 decimals of accuracy
[12:50:28][D][ntc:026]: 'Temperature' - Temperature: 19.7°C
[12:50:28][D][sensor:094]: 'Temperature': Sending state 19.73103 °C with 1 decimals of accuracy
[12:50:28][D][climate:396]: 'Thermostat' - Sending state:
[12:50:28][D][climate:399]:   Mode: HEAT
[12:50:28][D][climate:401]:   Action: IDLE
[12:50:28][D][climate:419]:   Current Temperature: 19.73°C
[12:50:28][D][climate:425]:   Target Temperature: 20.00°C
[12:50:35][D][sensor:094]: 'RSSI': Sending state -85.00000 dBm with 0 decimals of accuracy
[12:50:37][D][script.timer_page:3256]: Fallback to page Home
[12:50:38][D][text_sensor:064]: 'Current Page': Sending state 'home'
[12:50:38][D][script.page_changed:2644]: New page: home
[12:50:38][D][text_sensor:064]: 'Detailed Entity': Sending state ''
[12:50:38][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[12:50:38][D][nextion_textsensor:014]: Processed text_sensor "current_page" state "home"
[12:50:38][D][sensor:094]: 'ntc_source': Sending state 1.75183 V with 2 decimals of accuracy
[12:50:38][D][resistance:039]: 'resistance_sensor' - Resistance 12673.4Ω
[12:50:38][D][sensor:094]: 'resistance_sensor': Sending state 12673.40039 Ω with 1 decimals of accuracy
[12:50:38][D][ntc:026]: 'Temperature' - Temperature: 19.8°C
[12:50:38][D][sensor:094]: 'Temperature': Sending state 19.76186 °C with 1 decimals of accuracy
[12:50:38][D][climate:396]: 'Thermostat' - Sending state:
[12:50:38][D][climate:399]:   Mode: HEAT
[12:50:38][D][climate:401]:   Action: IDLE
[12:50:38][D][climate:419]:   Current Temperature: 19.76°C
[12:50:38][D][climate:425]:   Target Temperature: 20.00°C
[12:50:48][D][sensor:094]: 'ntc_source': Sending state 1.75183 V with 2 decimals of accuracy
[12:50:48][D][resistance:039]: 'resistance_sensor' - Resistance 12673.4Ω
[12:50:48][D][sensor:094]: 'resistance_sensor': Sending state 12673.40039 Ω with 1 decimals of accuracy
[12:50:48][D][ntc:026]: 'Temperature' - Temperature: 19.8°C
[12:50:48][D][sensor:094]: 'Temperature': Sending state 19.76186 °C with 1 decimals of accuracy
[12:50:48][D][climate:396]: 'Thermostat' - Sending state:
[12:50:48][D][climate:399]:   Mode: HEAT
[12:50:48][D][climate:401]:   Action: IDLE
[12:50:48][D][climate:419]:   Current Temperature: 19.76°C
[12:50:48][D][climate:425]:   Target Temperature: 20.00°C
[12:50:58][D][sensor:094]: 'ntc_source': Sending state 1.75217 V with 2 decimals of accuracy
[12:50:58][D][resistance:039]: 'resistance_sensor' - Resistance 12678.5Ω
[12:50:58][D][sensor:094]: 'resistance_sensor': Sending state 12678.54102 Ω with 1 decimals of accuracy
[12:50:58][D][ntc:026]: 'Temperature' - Temperature: 19.8°C
[12:50:58][D][sensor:094]: 'Temperature': Sending state 19.75305 °C with 1 decimals of accuracy
[12:50:58][D][climate:396]: 'Thermostat' - Sending state:
[12:50:58][D][climate:399]:   Mode: HEAT
[12:50:58][D][climate:401]:   Action: IDLE
[12:50:58][D][climate:419]:   Current Temperature: 19.75°C
[12:50:58][D][climate:425]:   Target Temperature: 20.00°C
[12:51:08][E][nextion:561]: ERROR: Received numeric return but next in queue "set_component_text" is not a valid sensor type 0
[12:51:08][D][sensor:094]: 'ntc_source': Sending state 1.75233 V with 2 decimals of accuracy
[12:51:08][D][resistance:039]: 'resistance_sensor' - Resistance 12681.1Ω
[12:51:08][D][sensor:094]: 'resistance_sensor': Sending state 12681.11133 Ω with 1 decimals of accuracy
[12:51:08][D][ntc:026]: 'Temperature' - Temperature: 19.7°C
[12:51:08][D][sensor:094]: 'Temperature': Sending state 19.74865 °C with 1 decimals of accuracy
[12:51:08][D][climate:396]: 'Thermostat' - Sending state:
[12:51:08][D][climate:399]:   Mode: HEAT
[12:51:08][D][climate:401]:   Action: IDLE
[12:51:08][D][climate:419]:   Current Temperature: 19.75°C
[12:51:08][D][climate:425]:   Target Temperature: 20.00°C
`

In the blueprint in climate I didn't configure anything, so that by-default it would use the internal thermostat.

**Comment by phendrickx** [comment]
I got it solved with a workaround in the blueprint-automation by selecting the nspanel-entity of itself.
Seems weird as the blueprint says to leave it empty to use the built-in thermostat.
![image](https://github.com/user-attachments/assets/d81cb547-8323-48c9-a570-2dda8af05eef)
