### ISSUE TITLE
Cover battery value (ikea blinds) are gone since 4.2.2 

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#1661]
### TFT Version

4.2.2

### ESPHome Version

4.2.2

### Blueprint Version

4.2.2

### Panel Model

NSPanel EU Model

### What is the bug?

battery status of Ikea fyrtur blinds are not shown anymore with 4.2.2

### Steps to Reproduce

<img width="418" alt="Bildschirmfoto 2024-01-17 um 09 36 41" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/109298227/e00c28ea-5696-4e57-8e96-942ab367a0ba">

**Comment by edwardtfn** [comment]
Fixed in `dev` and will be released with v4.2.3 soon.

**Comment by MarkuZP** [comment]
> Fixed in `dev` and will be released with v4.2.3 soon.

thank you!

**Comment by MarkuZP** [comment]
@edwardtfn I just upgraded to the latest 4.2.5 and its still not working ...

**Comment by edwardtfn** [comment]
Do you have all the 3 parts (TFT, ESPHome and Blueprint) with v4.2.5?

**Comment by MarkuZP** [comment]
Youre right. I found it out by myself just before you answered :-). My fault! It's working, thank you so much !!!! :-) Nice work!!!!  one question: How comes that the blueprint was still he older version? I copy & pasted it directly from the code page and then I tried to copy it from the download into the blueprints folder but the version was still the old one. Now its working but why?

**Comment by MarkuZP** [comment]
Thank you edward! Nice feature!
