### ISSUE TITLE
`Bug` not sure, are 'left_bt_pic' and 'right_bt_pic' changed?

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#1904]
### TFT Version

4.3

### ESPHome Version

4.3

### Blueprint Version

4.3

### Panel Model

EU

### What is the bug?

refresh_relays
does not update hw buttons anymore
this fails
```
          if (id(relay_settings) & nspanel_ha_blueprint::RelaySettings::Relay1_Local) disp1->send_command_printf("home.left_bt_pic.val=%i", (relay_1->state) ? 1 : 0);
          if (id(relay_settings) & nspanel_ha_blueprint::RelaySettings::Relay2_Local) disp1->send_command_printf("home.right_bt_pic.val=%i", (relay_2->state) ? 1 : 0);
```
I removed the `if `statement, but didn't help.
I think `home.left_bt_pic.` and `home.right_bt_pic` are renamed because they are now on all pages.
however I cannot find the bars in the latest hmi file?
maybe they are created magically, I don't know, but I cannot find them So I don't know for sure.

edit:
shoud `refresh_relays`
use
`refresh_hardware_buttons_bars->execute();`
instead?
my lambda knowledge is a little weak, so there might be a syntax error in here.

### Steps to Reproduce

make sure local control is enabled,
toggle the switches.
you will see, `home_relay1_icon` and `home_relay2_icon` will respond instand, while you have to wait a sec for the bars to be changed.

**Comment by edwardtfn** [comment]
That's right, the buttons are now plotted dynamically from ESPHome, so N o  component on the HMI.
The plot is done by script `refresh_hardware_buttons_bars`, which should be included on the relays `on_change` event, but that is probably missing.

I will take a look at this tomorrow.

**Comment by edwardtfn** [comment]
By the way, this delay was there before, as those bars have always been controlled by the Blueprint. I probably have to handle that I a different way to be able to control the bars statuses locally.

**Comment by bkbartk** [comment]
those bars were controlled locally.
the physical relays contain
```
    on_turn_on:
      then:
        - script.execute: refresh_relays
    on_turn_off:
      then:
        - script.execute: refresh_relays
```

refresh_relays still is like this
```

  - id: refresh_relays
    mode: restart
    then:
      - lambda: |-
          // Chips - Relays
          disp1->set_component_text_printf("home.chip_relay1", "%s", (relay_1->state) ? id(home_relay1_icon) : "\uFFFF");
          disp1->set_component_text_printf("home.chip_relay2", "%s", (relay_2->state) ? id(home_relay2_icon) : "\uFFFF");
          // Hardware buttons bars - Fallback mode
          if (id(relay_settings) & nspanel_ha_blueprint::RelaySettings::Relay1_Local) disp1->send_command_printf("home.left_bt_pic.val=%i", (relay_1->state) ? 1 : 0);
          if (id(relay_settings) & nspanel_ha_blueprint::RelaySettings::Relay2_Local) disp1->send_command_printf("home.right_bt_pic.val=%i", (relay_2->state) ? 1 : 0);

```
which ofc doesn't work anymore
but if I change it to this
```
  - id: refresh_relays
    mode: restart
    then:
      - lambda: |-
          // Chips - Relays
          disp1->set_component_text_printf("home.chip_relay1", "%s", (relay_1->state) ? id(home_relay1_icon) : "\uFFFF");
          disp1->set_component_text_printf("home.chip_relay2", "%s", (relay_2->state) ? id(home_relay2_icon) : "\uFFFF");
          refresh_hardware_buttons_bars->execute();
```
it still fails to work, not sure why, I have a hard time wrapping my head around the conditions in refresh_hardware_buttons_bars
probably I'm missing some cpp/lambda knowledge here.

**Comment by edwardtfn** [comment]
You are totally right!! 😃 

I've just pushed a fix to `dev`. I couldn't test it yet, will do it tomorrow.

**Comment by ademobile** [comment]
As I use hue light scenes that can be multistates, I used to set the bars by a service call to allow someone to know lights were on or off, espically lights that cannot be seen. In this update the 'feature' has been removed. Is there still a way of doing this?

Code I used that now does not work:

`service: esphome.nspanel_86_lr_send_command_printf
data:
  cmd: home.right_bt_pic.val=1`

**Comment by bkbartk** [comment]
Sorry to bother,
but it seems to work for turn_on, not for turn_off somehow.
I think,
`(((id(relay_settings) & RelaySettings::Relay2_Local) and relay_2->state) or (id(buttons_settings) & ButtonSettings::ButtonRight_State)) 
? id(buttons_color_on) : id(buttons_color_off))`
should be something like
`(((id(relay_settings) & RelaySettings::Relay2_Local) and relay_2->state) or (!(id(relay_settings) & RelaySettings::Relay2_Local) and id(buttons_settings) & ButtonSettings::ButtonRight_State)) 
? id(buttons_color_on) : id(buttons_color_off))`
else the righthand side part still suffice on turn_off
but I'm not 100% sure how it works.

**Comment by bkbartk** [comment]
I almost have a fix for this,
made a mistake to apply `relay_1` state twice,
will do some more testing and create a PR

**Comment by bkbartk** [comment]
I created a pull request
https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/1950
did a little bit of code cleanup, this can be better I know, but at that point I need to know the meaning of all variables and I just don't at the moment.

**Comment by bkbartk** [comment]
I need a little help with my pull request, it says
```
In lambda function:\n.test/../esphome/nspanel_esphome_core.yaml:1702:7: error: 'cJSON' was not declared in this scope\n.test/../esphome/nspanel_esphome_core.yaml:1702:19: error: expected primary-expression before '=' token\n.test/../esphome/nspanel_esphome_core.yaml:1702:21: error: 'cJSON_Parse' was not declared in this scope\n.test/../esphome/nspanel_esphome_core.yaml:1703:16: error: expected primary-expression before ')' token\n.test/../esphome/nspanel_esphome_core.yaml:1706:15: error: 'cJSON' does not name a 
```
but that part is not something I touched, becided that, the code builds perfectly for me on esphome 2024.3.0

**Comment by edwardtfn** [comment]
> Sorry to bother, but it seems to work for turn_on, not for turn_off somehow. I think, `(((id(relay_settings) & RelaySettings::Relay2_Local) and relay_2->state) or (id(buttons_settings) & ButtonSettings::ButtonRight_State)) ? id(buttons_color_on) : id(buttons_color_off))` should be something like `(((id(relay_settings) & RelaySettings::Relay2_Local) and relay_2->state) or (!(id(relay_settings) & RelaySettings::Relay2_Local) and id(buttons_settings) & ButtonSettings::ButtonRight_State)) ? id(buttons_color_on) : id(buttons_color_off))` else the righthand side part still suffice on turn_off but I'm not 100% sure how it works.

It was correct.
`(id(relay_settings) & RelaySettings::Relay2_Local) and relay_2->state)` <= Turn on if the relay is controlled local and is enabled.
or
`(id(buttons_settings) & ButtonSettings::ButtonRight_State)) ? id(buttons_color_on) : id(buttons_color_off))` <= Turn on if the button was set to `on` via service.

**Comment by bkbartk** [comment]
I will try to explain

I use local control

so when I turn the switch to _off using the hw buttons, not the service
`(id(buttons_settings) & ButtonSettings::ButtonRight_State))` 
still returns true, directly after pressing the button.
so at that point the bar stays on until the HA blueprint catches up

**Comment by edwardtfn** [comment]
> I need a little help with my pull request, it says
> 
> ```
> In lambda function:\n.test/../esphome/nspanel_esphome_core.yaml:1702:7: error: 'cJSON' was not declared in this scope\n.test/../esphome/nspanel_esphome_core.yaml:1702:19: error: expected primary-expression before '=' token\n.test/../esphome/nspanel_esphome_core.yaml:1702:21: error: 'cJSON_Parse' was not declared in this scope\n.test/../esphome/nspanel_esphome_core.yaml:1703:16: error: expected primary-expression before ')' token\n.test/../esphome/nspanel_esphome_core.yaml:1706:15: error: 'cJSON' does not name a 
> ```
> 
> but that part is not something I touched, becided that, the code builds perfectly for me on esphome 2024.3.0
This should be fixed now.

**Comment by edwardtfn** [comment]
> I will try to explain
> 
> I use local control
> 
> so when I turn the switch to _off using the hw buttons, not the service `(id(buttons_settings) & ButtonSettings::ButtonRight_State))` still returns true, directly after pressing the button. so at that point the bar stays on until the HA blueprint catches up

Yeah... There's an error. The local controlled relay should change the button state and that code is missing. :(
This is probably the source of bug reported on #1933.

I will look at that.

**Comment by bkbartk** [comment]
> This should be fixed now.

Still the same issue.

> Yeah... There's an error. The local controlled relay should change the button state and that code is missing. :(
This is probably the source of bug reported on https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1933.

Clear, then the bug is somewhere else, and you can skip my PR, however the cleanup I did makes it a little more readable.

**Comment by edwardtfn** [comment]
I believe https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/6d5af5a6e064a06dbb86bcf86b53234f54392d15 fixes this issue, allowing you to control the bars independently.
Please let me know if you have a chance to try it.

**Comment by bkbartk** [comment]
I updated 1 of my devices to dev and all seems to be working ok.
found 1 other unralated issue, will try to report this later
