### ISSUE TITLE
Import of Blueprint in Home Assistant keeps failing

### ISSUE THREAD

**Issue by bregtvandenbergh** [Blackymas/NSPanel_HA_Blueprint#2554]
### TFT Version

4.3.13

### Firmware Version

4.3.13

### Blueprint Version

4.3.15

### Panel Model

EU

### What is the bug?

Hi everybody

As result of some issues with updates there is a resolution for the bootloop issue as is there is now a new version 4.3.14.
When I try to import the updated Blueprints, I get the following error:

![Image](https://github.com/user-attachments/assets/674a2000-49ea-434a-aafc-1e2c721776cd)

Can anyone help with this please?

Kind regards

### Your Panel's YAML

```yaml

```

**Comment by edwardtfn** [comment]
Which version of Home Assistant are you running? My trying to duplicate this, but everything works fine on my side.

**Comment by bregtvandenbergh** [comment]
I'm using 

![Image](https://github.com/user-attachments/assets/fd990bb4-1206-4360-b978-7beaeb4eb4eb)

What I managed to find out that when I redirect directly to the Github page it gives an error, when I use the import blueprint button: 

![Image](https://github.com/user-attachments/assets/98e8902e-0136-4be3-9e5e-043a944aa457) then I can load it. but I can only load the main branche and not the one where the bug is fixed.

**Comment by bregtvandenbergh** [comment]
When I try to upload it manually i get the following error in HA:

New Automation Installation Failed

Your new automation has been saved, but the installation timed out. This may be due to errors when parsing configuration.yaml. Check the configuration in the developer tools. Your automation will only become visible once this is corrected and automations have been reloaded. Changes to room, category, or labels were not saved and will need to be applied again.

**Comment by bregtvandenbergh** [comment]
![Image](https://github.com/user-attachments/assets/9b3e4771-4892-4dc4-8c16-f1372b588006)

**Comment by edwardtfn** [comment]
The bug is fixed in the main branch...

**Comment by bregtvandenbergh** [comment]
Hi @edwardtfn , still getting following error when trying to save the blueprint:

**New Automation Installation Failed

Your new automation has been saved, but the installation timed out. This may be due to errors when parsing configuration.yaml. Check the configuration in the developer tools. Your automation will only become visible once this is corrected and automations have been reloaded. Changes to room, category, or labels were not saved and will need to be applied again.**

![Image](https://github.com/user-attachments/assets/b4ba8f0b-a8df-4a34-b60d-12e03f2ea8b9)

Not finding any problems via the developer tools.

Kind regards

**Comment by bregtvandenbergh** [comment]
@edwardtfn 

LOG NSPanel:

[15:18:16][C][nspanel_ha_blueprint:2224]: Wi-Fi:         Good (-57 dBm)
[15:18:16][C][nspanel_ha_blueprint:2235]: API:           Connected
[15:18:16][C][nspanel_ha_blueprint:2243]: Blueprint:
[15:18:16][W][nspanel_ha_blueprint:2248]:   Init steps:  0 (0.0%)
[15:18:16][W][nspanel_ha_blueprint:2249]:   State:       Pending
[15:18:16][C][nspanel_ha_blueprint:2250]: Requesting blueprint settings
[15:18:16][D][script:077]: Script 'boot_event' restarting (mode: restart)
[15:18:16][C][nspanel_ha_blueprint:2255]: ESPHome:
[15:18:16][C][nspanel_ha_blueprint:2256]:   Version:     4.3.13
[15:18:16][C][nspanel_ha_blueprint:2257]:   Compiler:    2025.5.1
[15:18:16][C][nspanel_ha_blueprint:2262]:   Framework:   ESP-IDF
[15:18:16][C][nspanel_ha_blueprint:2267]:   Free heap:
[15:18:16][C][nspanel_ha_blueprint:2270]:     Internal:   166248 bytes (48.3%)
[15:18:16][C][nspanel_ha_blueprint:2280]:     PSRAM:     2005256 bytes (96.2%)
[15:18:16][C][nspanel_ha_blueprint:2288]: UART:
[15:18:16][C][nspanel_ha_blueprint:2289]:   Baud rate:   115200 bps
[15:18:16][C][nspanel_ha_blueprint:2290]:   Queue size:  0
[15:18:16][C][nspanel_ha_blueprint:2294]: Nextion:
[15:18:16][C][nspanel_ha_blueprint:2295]:   Queue size:  0
[15:18:16][C][nspanel_ha_blueprint:2297]:   Is setup:    True
[15:18:16][C][nspanel_ha_blueprint:2304]:   Init:        True
[15:18:16][C][nspanel_ha_blueprint:2310]:   TFT:         4.3.13
[15:18:16][C][nspanel_ha_blueprint:2311]: Packages:
[15:18:16][C][nspanel_ha_blueprint:2313]:   - Core
[15:18:16][C][nspanel_ha_blueprint:2322]:   - Upload TFT
[15:18:16][C][nspanel_ha_blueprint:2325]:   - Climate - Base
[15:18:16][C][nspanel_ha_blueprint:2334]:   - Climate - Heat
[15:18:16][C][nspanel_ha_blueprint:097]: Add-on Upload TFT:
[15:18:16][C][nspanel_ha_blueprint:098]:   File model: NSPanel EU
[15:18:16][C][nspanel_ha_blueprint:099]:   Valid TFT:  YES
[15:18:16][C][nspanel_ha_blueprint:131]: Add-on climate:
[15:18:16][C][nspanel_ha_blueprint:140]:   Heat:  Enabled
[15:18:16][E][nspanel_ha_blueprint:144]:   Relay: 0
[15:18:16][W][component:257]: Component script took a long time for an operation (52 ms).
[15:18:16][W][component:258]: Components should block for at most 30 ms.

**Comment by edwardtfn** [comment]
I have no idea why your automation is failing to parse. It's a big one, but it is working for many people.
In the end, can you see the automation under the folder blueprints/automation/Blackymas?

**Comment by bregtvandenbergh** [comment]
Sadly is HA core installed in a docker on Cosmos Server.
I tried to get access to the files to look but I'm not able to.

Any other suggestions?
Maybe where I can change the timeout?

[15:18:16][W][component:257]: Component script took a long time for an operation (52 ms).
[15:18:16][W][component:258]: Components should block for at most 30 ms.

Kind regards

**Comment by bregtvandenbergh** [comment]
I don't know what 

"script: "\uEBC1"                   # mdi:script-text" 

is but could that be the problem?

Can I disable or remove it to try?

Kind regards

**Comment by edwardtfn** [comment]
> Sadly is HA core installed in a docker on Cosmos Server. I tried to get access to the files to look but I'm not able to.
> 
> Any other suggestions? Maybe where I can change the timeout?
> 
> [15:18:16][W][component:257]: Component script took a long time for an operation (52 ms). [15:18:16][W][component:258]: Components should block for at most 30 ms.
> 
> Kind regards

This message from ESPHome log is not connected to the issue with your blueprint import. The log message says some of the scripts in the firmware is taking more than 30ms.
We do have some scripts that waits for the blueprint, so it could be that a non-responsive blueprint will drive to that message, but anyhow, 52ms isn't a big issue.
I wouldn't focus that much on this message now.

**Comment by edwardtfn** [comment]
> I don't know what
> 
> "script: "\uEBC1" # mdi:script-text"
> 
> is but could that be the problem?
> 
> Can I disable or remove it to try?
> 
> Kind regards

Remove it could break something. You could instead use like `script: X` and it should give similar result, but it will show a `X` instead of the icon related to script on the places (buttons) where you assigned a script.

This is not connected to that message you have on ESPHome.

Anyways, how you see this line of code? Can you edit the Blueprint code in your Home Assistant?

**Comment by bregtvandenbergh** [comment]
I can see it in esphome.
I can control the panel from HA without a problem, just unable to send the blueprint to the device.

![Image](https://github.com/user-attachments/assets/273abea9-efb1-42a1-9086-5ff759a752fb)

I'll keep searching ;)

**Comment by edwardtfn** [comment]
> just unable to send the blueprint to the device.

You mean importing the Blueprint to Home Assistant, right?

If you go Settings > Automations and then select the tab Blueprints, can you see "NSPanel configuration" in the list?

**Comment by edwardtfn** [comment]
> ![Image](https://github.com/user-attachments/assets/674a2000-49ea-434a-aafc-1e2c721776cd)

On this screen, please try to import from this url: `https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_blueprint.yaml`

**Comment by bregtvandenbergh** [comment]
This is exactly what I am doing:

![Image](https://github.com/user-attachments/assets/d92b5e2a-cfc7-4fb8-a3ad-8ff90aa2d9ed)

![Image](https://github.com/user-attachments/assets/28acb6ce-7249-46df-bd96-f3b56d76649b)

![Image](https://github.com/user-attachments/assets/dc38d96e-4d26-4336-9940-273dc319fa69)

![Image](https://github.com/user-attachments/assets/79f21555-e50c-44e8-b71d-109fc48d2465)

![Image](https://github.com/user-attachments/assets/2273fdeb-c616-4869-b66e-eca062301ce3)

I saw on another forum if i could connect to it locally and not externally that it should work but I'm not able to.
I don't know how.

kr

**Comment by bregtvandenbergh** [comment]
Hi @edwardtfn 

I have an update.
I created a new standalone HA on a rPi.
Here I got the same error but it did it just in time.
This means I got it working for now.

On the original HA instance. I got the blueprint installed on HA but when I configured it, it went in timeout.
So it never appeared under the automations tab but it did under the blueprint tab.

So I found a workaround but still strange.

I really want to thank you for guiding me in the correct way ;)

Kind regards

**Comment by edwardtfn** [comment]
> when I configured it, it went in timeout.

When you say it timed out, do you mean this message?

> ![Image](https://github.com/user-attachments/assets/b4ba8f0b-a8df-4a34-b60d-12e03f2ea8b9)

If so, when that message appears? When you try to save the automation or when you are opening the automation?

I see some fields filled already... Does that means you can edit it or this is due to and over version installed? If that is the case, from which older version are you updating from?

**Comment by bregtvandenbergh** [comment]
- I can install the blueprint
- I can configure the blueprint

It gives the above error "new automation installation failed" about 5 seconds after I click save.
Nothing appears under the tab 'automations'

**Comment by bregtvandenbergh** [comment]
Hi @edwardtfn 

Found the issue.

automation: !include automations.yaml
scene: !include scenes.yaml

added to configuration.yaml after getting access to the files.

My apologies ;)

Kind regards
