### ISSUE TITLE
System Data ERROR! and TFT version 000.000

### ISSUE THREAD

**Issue by Fynnmk** [Blackymas/NSPanel_HA_Blueprint#2590]
### TFT Version

000.000

### Firmware Version

4.3.15 (ESPHome 2025.7.0-dev)

### Blueprint Version

4.3.15

### Panel Model

EU

### What is the bug?

![Image](https://github.com/user-attachments/assets/7433ff70-34a4-4161-8dbb-f95a9a27c844)
![Image](https://github.com/user-attachments/assets/d8fac785-e883-4b5c-a492-637c8073d4f8)

Hi I am new with Home Assistant and the Nspanel.
I have all as described in the instructions. Unfortunately I get the "Data Error system!". In addition, the message is shown to me in Home Assistant that the TFT version is 000,000.
But when I select the Blank.Tft file via the menu, everything works great. However, if I then install the EU version again, the same errors come again and in the log: "[W] [NEXION: 477]: Invalide variable name"

I've tried a lot, but nothing works :/

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel"
  friendly_name: "nspanel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

### ESPHome Logs

INFO ESPHome 2025.7.0-dev
INFO Reading configuration /config/esphome/nspanal.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@v4.3.15
INFO Detected timezone 'Europe/Berlin'
WARNING The 'publish_initial_state' option has been replaced by 'trigger_on_initial_state' and will be removed in a future release
INFO Starting log output from 192.168.178.133 using esphome API
INFO Successfully resolved nspanel @ 192.168.178.133 in 0.000s
INFO Successfully connected to nspanel @ 192.168.178.133 in 0.055s
INFO Successful handshake with nspanel @ 192.168.178.133 in 0.025s
[17:24:40][I][app:137]: ESPHome version 2025.7.0-dev compiled on Jun 13 2025, 16:36:13
[17:24:40][I][app:139]: Project esphome.NSPanel_HA_Blueprint version 4.3.15
[17:24:40][C][wifi:613]: WiFi:
[17:24:40][C][wifi:434]:   Local MAC: E4:65:B8:48:6E:24
[17:24:40][C][wifi:439]:   SSID: [redacted]
[17:24:40][C][wifi:442]:   IP Address: 192.168.178.133
[17:24:40][C][wifi:446]:   BSSID: [redacted]
[17:24:40][C][wifi:446]:   Hostname: 'nspanel'
[17:24:40][C][wifi:446]:   Signal strength: -58 dB ▂▄▆█
[17:24:40][C][wifi:455]:   Channel: 1
[17:24:40][C][wifi:455]:   Subnet: 255.255.255.0
[17:24:40][C][wifi:455]:   Gateway: 192.168.178.1
[17:24:40][C][wifi:455]:   DNS1: 192.168.178.1
[17:24:40][C][wifi:455]:   DNS2: 0.0.0.0
[17:24:40][W][nextion:477]: Invalid variable name
[17:24:40][W][nextion:477]: Invalid variable name
[17:24:40][C][logger:224]: Logger:
[17:24:40][C][logger:224]:   Max Level: DEBUG
[17:24:40][C][logger:224]:   Initial Level: DEBUG
[17:24:40][C][logger:230]:   Log Baud Rate: 0
[17:24:40][C][logger:230]:   Hardware UART: UART0
[17:24:40][C][logger:237]:   Task Log Buffer Size: 768
[17:24:40][C][uart.idf:159]: UART Bus 0:
[17:24:40][C][uart.idf:160]:   TX Pin: GPIO16
[17:24:40][C][uart.idf:161]:   RX Pin: GPIO17
[17:24:40][C][uart.idf:163]:   RX Buffer Size: 256
[17:24:40][C][uart.idf:165]:   Baud Rate: 115200 baud
[17:24:40][C][uart.idf:165]:   Data Bits: 8
[17:24:40][C][uart.idf:165]:   Parity: NONE
[17:24:40][C][uart.idf:165]:   Stop bits: 1
[17:24:40][C][ledc.output:182]: Output:
[17:24:40][C][ledc.output:183]:   Pin GPIO21
[17:24:40][C][ledc.output:184]:   Channel: 0
[17:24:40][C][ledc.output:184]:   PWM Frequency: 1000.0 Hz
[17:24:40][C][ledc.output:184]:   Phase angle: 0.0°
[17:24:40][C][ledc.output:184]:   Bit depth: 16
[17:24:41][C][template.binary_sensor:020]: Template Binary Sensor 'Nextion display'
[17:24:41][C][template.binary_sensor:020]:   Device Class: 'connectivity'
[17:24:41][C][template.number:050]: Template Number 'Display Brightness'
[17:24:41][C][template.number:050]:   Unit of Measurement: '%'
[17:24:41][C][template.number:051]:   Optimistic: YES
[17:24:41][C][template.number:052]:   Update Interval: 60.0s
[17:24:41][C][template.number:050]: Template Number 'Display Brightness Dimdown'
[17:24:41][C][template.number:050]:   Unit of Measurement: '%'
[17:24:41][C][template.number:051]:   Optimistic: YES
[17:24:41][C][template.number:052]:   Update Interval: 60.0s
[17:24:41][C][template.number:050]: Template Number 'Display Brightness Sleep'
[17:24:41][C][template.number:050]:   Unit of Measurement: '%'
[17:24:41][C][template.number:051]:   Optimistic: YES
[17:24:41][C][template.number:052]:   Update Interval: 60.0s
[17:24:41][C][template.number:050]: Template Number 'Temperature Correction'
[17:24:41][C][template.number:050]:   Unit of Measurement: '°C'
[17:24:41][C][template.number:051]:   Optimistic: YES
[17:24:41][C][template.number:052]:   Update Interval: 60.0s
[17:24:41][C][template.number:050]: Template Number 'Timeout Page'
[17:24:41][C][template.number:050]:   Icon: 'mdi:timer'
[17:24:41][C][template.number:050]:   Unit of Measurement: 's'
[17:24:41][C][template.number:051]:   Optimistic: YES
[17:24:41][C][template.number:052]:   Update Interval: 60.0s
[17:24:41][C][template.number:050]: Template Number 'Timeout Dimming'
[17:24:41][C][template.number:050]:   Icon: 'mdi:timer'
[17:24:41][C][template.number:050]:   Unit of Measurement: 's'
[17:24:41][C][template.number:051]:   Optimistic: YES
[17:24:41][C][template.number:052]:   Update Interval: 60.0s
[17:24:41][C][template.number:050]: Template Number 'Timeout Sleep'
[17:24:41][C][template.number:050]:   Icon: 'mdi:timer'
[17:24:41][C][template.number:050]:   Unit of Measurement: 's'
[17:24:41][C][template.number:051]:   Optimistic: YES
[17:24:41][C][template.number:052]:   Update Interval: 60.0s
[17:24:41][C][template.select:065]: Template Select 'Baud rate'
[17:24:41][C][template.select:065]:   Icon: 'mdi:swap-horizontal'
[17:24:41][C][template.select:066]:   Update Interval: 60.0s
[17:24:41][C][template.select:069]:   Optimistic: YES
[17:24:41][C][template.select:069]:   Initial Option: 115200
[17:24:41][C][template.select:069]:   Restore Value: YES
[17:24:41][C][template.select:065]: Template Select 'Wake-up page'
[17:24:41][C][template.select:065]:   Icon: 'mdi:page-next-outline'
[17:24:41][C][template.select:066]:   Update Interval: 60.0s
[17:24:41][C][template.select:069]:   Optimistic: YES
[17:24:41][C][template.select:069]:   Initial Option: home
[17:24:41][C][template.select:069]:   Restore Value: YES
[17:24:41][C][template.select:065]: Template Select 'Update TFT display - Model'
[17:24:41][C][template.select:065]:   Icon: 'mdi:file-sync'
[17:24:41][C][template.select:066]:   Update Interval: 60.0s
[17:24:41][C][template.select:069]:   Optimistic: YES
[17:24:41][C][template.select:069]:   Initial Option: NSPanel EU
[17:24:41][C][template.select:069]:   Restore Value: YES
[17:24:41][C][template.select:065]: Template Select 'Update TFT display - Baud rate'
[17:24:41][C][template.select:065]:   Icon: 'mdi:swap-horizontal'
[17:24:41][C][template.select:066]:   Update Interval: 60.0s
[17:24:41][C][template.select:069]:   Optimistic: YES
[17:24:41][C][template.select:069]:   Initial Option: 921600
[17:24:41][C][template.select:069]:   Restore Value: YES
[17:24:41][C][switch.gpio:079]: GPIO Switch 'Nextion display - Power'
[17:24:41][C][switch.gpio:079]:   Restore Mode: always ON
[17:24:41][C][switch.gpio:031]:   Pin: GPIO4
[17:24:41][C][template.text_sensor:020]: Template Sensor 'Device Name'
[17:24:41][C][template.text_sensor:020]:   Icon: 'mdi:identifier'
[17:24:41][C][template.text_sensor:020]: Template Sensor 'Detailed Entity'
[17:24:41][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[17:24:41][C][template.text_sensor:020]: Template Sensor 'Notification Label'
[17:24:41][C][template.text_sensor:020]: Template Sensor 'Notification Text'
[17:24:41][C][template.text_sensor:020]: Template Sensor 'Version Blueprint'
[17:24:41][C][template.text_sensor:020]:   Icon: 'mdi:tag-text-outline'
[17:24:41][C][template.text_sensor:020]: Template Sensor 'Version ESPHome'
[17:24:41][C][template.text_sensor:020]:   Icon: 'mdi:tag-text-outline'
[17:24:41][C][template.sensor:022]: Template Sensor 'Blueprint'
[17:24:41][C][template.sensor:022]:   State Class: ''
[17:24:41][C][template.sensor:022]:   Unit of Measurement: '%'
[17:24:41][C][template.sensor:022]:   Accuracy Decimals: 1
[17:24:41][C][template.sensor:022]:   Icon: 'mdi:link-variant'
[17:24:41][C][template.sensor:023]:   Update Interval: 60.0s
[17:24:41][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Left Button'
[17:24:41][C][gpio.binary_sensor:016]:   Pin: GPIO14
[17:24:41][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Right Button'
[17:24:41][C][gpio.binary_sensor:016]:   Pin: GPIO27
[17:24:41][C][switch.gpio:079]: GPIO Switch 'Relay 1'
[17:24:41][C][switch.gpio:079]:   Restore Mode: restore defaults to OFF
[17:24:41][C][switch.gpio:031]:   Pin: GPIO22
[17:24:41][C][switch.gpio:079]: GPIO Switch 'Relay 2'
[17:24:41][C][switch.gpio:079]:   Restore Mode: restore defaults to OFF
[17:24:41][C][switch.gpio:031]:   Pin: GPIO19
[17:24:41][C][template.switch:079]: Template Switch 'Notification unread'
[17:24:41][C][template.switch:079]:   Restore Mode: always OFF
[17:24:41][C][template.switch:057]:   Optimistic: YES
[17:24:41][C][template.switch:079]: Template Switch 'Notification sound'
[17:24:41][C][template.switch:079]:   Restore Mode: restore defaults to OFF
[17:24:41][C][template.switch:057]:   Optimistic: YES
[17:24:41][C][psram:018]: PSRAM:
[17:24:41][C][psram:022]:   Available: YES
[17:24:41][C][psram:024]:   Size: 2048 KB
[17:24:41][C][rtttl:030]: Rtttl:
[17:24:41][C][rtttl:030]:   Gain: 0.600000
[17:24:41][C][nextion:149]: Nextion:
[17:24:41][C][nextion:153]:   Device Model:   NX4832F035_011C
[17:24:41][C][nextion:153]:   FW Version:     110
[17:24:41][C][nextion:153]:   Serial Number:  32B434018D47B237
[17:24:41][C][nextion:153]:   Flash Size:     16777216
[17:24:41][C][nextion:161]:   Wake On Touch:  YES
[17:24:41][C][nextion:161]:   Exit reparse:   YES
[17:24:41][C][factory_reset.button:011]: Factory Reset Button 'Factory reset'
[17:24:41][C][factory_reset.button:011]:   Icon: 'mdi:restart-alert'
[17:24:41][C][restart.button:017]: Restart Button 'Restart'
[17:24:41][C][restart.button:017]:   Icon: 'mdi:restart'
[17:24:41][C][adc.esp32:058]: ADC Sensor 'ntc_source'
[17:24:41][C][adc.esp32:058]:   State Class: 'measurement'
[17:24:41][C][adc.esp32:058]:   Unit of Measurement: 'V'
[17:24:41][C][adc.esp32:058]:   Accuracy Decimals: 2
[17:24:41][C][adc.esp32:058]:   Device Class: 'voltage'
[17:24:41][C][adc.esp32:059]:   Pin: GPIO38
[17:24:41][C][adc.esp32:074]:   Attenuation: 12db
[17:24:41][C][adc.esp32:080]:   Samples: 4
[17:24:41][C][adc.esp32:080]:   Sampling mode: average
[17:24:41][C][adc.esp32:084]:   Update Interval: 10.0s
[17:24:41][C][resistance:010]: Resistance Sensor 'resistance_sensor'
[17:24:41][C][resistance:010]:   State Class: 'measurement'
[17:24:41][C][resistance:010]:   Unit of Measurement: 'Ω'
[17:24:41][C][resistance:010]:   Accuracy Decimals: 1
[17:24:41][C][resistance:010]:   Icon: 'mdi:flash'
[17:24:41][C][resistance:011]:   Configuration: DOWNSTREAM
[17:24:41][C][resistance:011]:   Resistor: 11200.00Ω
[17:24:41][C][resistance:011]:   Reference Voltage: 3.3V
[17:24:41][C][ntc:014]: NTC Sensor 'Temperature'
[17:24:41][C][ntc:014]:   State Class: 'measurement'
[17:24:41][C][ntc:014]:   Unit of Measurement: '°C'
[17:24:41][C][ntc:014]:   Accuracy Decimals: 1
[17:24:41][C][ntc:014]:   Device Class: 'temperature'
[17:24:42][C][homeassistant.time:010]: Home Assistant Time:
[17:24:42][C][homeassistant.time:010]:   Timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
[17:24:42][C][esphome.ota:073]: Over-The-Air updates:
[17:24:42][C][esphome.ota:073]:   Address: nspanel.local:3232
[17:24:42][C][esphome.ota:073]:   Version: 2
[17:24:42][C][esphome.ota:080]:   Password configured
[17:24:42][C][safe_mode:018]: Safe Mode:
[17:24:42][C][safe_mode:019]:   Boot considered successful after 60 seconds
[17:24:42][C][safe_mode:019]:   Invoke after 3 boot attempts
[17:24:42][C][safe_mode:019]:   Remain for 180 seconds
[17:24:42][C][api:182]: API Server:
[17:24:42][C][api:182]:   Address: nspanel.local:6053
[17:24:42][C][api:192]:   Using noise encryption: NO
[17:24:42][C][wifi_signal.sensor:010]: WiFi Signal 'RSSI'
[17:24:42][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[17:24:42][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[17:24:42][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[17:24:42][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[17:24:42][C][wifi_signal.sensor:010]:   Icon: 'mdi:wifi'
[17:24:42][C][mdns:122]: mDNS:
[17:24:42][C][mdns:122]:   Hostname: nspanel
[17:24:47][D][sensor:093]: 'ntc_source': Sending state 1.39900 V with 2 decimals of accuracy
[17:24:47][D][resistance:042]: 'resistance_sensor' - Resistance 8242.4Ω
[17:24:47][D][sensor:093]: 'resistance_sensor': Sending state 8242.39941 Ω with 1 decimals of accuracy
[17:24:47][D][ntc:026]: 'Temperature' - Temperature: 29.4°C
[17:24:47][D][sensor:093]: 'Temperature': Sending state 29.41441 °C with 1 decimals of accuracy
[17:24:47][W][nextion:477]: Invalid variable name
[17:24:50][C][nspanel_ha_blueprint:2230]: Wi-Fi:         Good (-58 dBm)
[17:24:50][C][nspanel_ha_blueprint:2241]: API:           Connected
[17:24:50][C][nspanel_ha_blueprint:2249]: Blueprint:
[17:24:50][C][nspanel_ha_blueprint:2251]:   Version:     4.3.15
[17:24:50][C][nspanel_ha_blueprint:2252]:   Init steps:  62 (100.0%)
[17:24:50][C][nspanel_ha_blueprint:2261]: ESPHome:
[17:24:50][C][nspanel_ha_blueprint:2262]:   Version:     4.3.15
[17:24:50][C][nspanel_ha_blueprint:2263]:   Compiler:    2025.7.0-dev
[17:24:50][C][nspanel_ha_blueprint:2268]:   Framework:   ESP-IDF
[17:24:50][C][nspanel_ha_blueprint:2273]:   Free heap:
[17:24:50][C][nspanel_ha_blueprint:2276]:     Internal:   191220 bytes (56.3%)
[17:24:50][C][nspanel_ha_blueprint:2286]:     PSRAM:     2012532 bytes (96.6%)
[17:24:50][C][nspanel_ha_blueprint:2294]: UART:
[17:24:50][C][nspanel_ha_blueprint:2295]:   Baud rate:   115200 bps
[17:24:50][C][nspanel_ha_blueprint:2296]:   Queue size:  0
[17:24:50][C][nspanel_ha_blueprint:2300]: Nextion:
[17:24:50][C][nspanel_ha_blueprint:2301]:   Queue size:  0
[17:24:50][C][nspanel_ha_blueprint:2303]:   Is setup:    True
[17:24:50][C][nspanel_ha_blueprint:2310]:   Init:        True
[17:24:50][W][nspanel_ha_blueprint:2314]:   TFT:         UNKNOWN
[17:24:50][C][nspanel_ha_blueprint:2317]: Packages:
[17:24:50][C][nspanel_ha_blueprint:2319]:   - Core
[17:24:50][C][nspanel_ha_blueprint:2328]:   - Upload TFT
[17:24:50][C][nspanel_ha_blueprint:097]: Add-on Upload TFT:
[17:24:50][C][nspanel_ha_blueprint:098]:   File model: NSPanel Blank
[17:24:50][C][nspanel_ha_blueprint:099]:   Valid TFT:  NO
[17:24:50][W][component:257]: Component script took a long time for an operation (87 ms).
[17:24:50][W][component:258]: Components should block for at most 30 ms.
[17:24:57][D][sensor:093]: 'RSSI': Sending state -56.00000 dBm with 0 decimals of accuracy
[17:24:57][D][sensor:093]: 'ntc_source': Sending state 1.39800 V with 2 decimals of accuracy
[17:24:57][D][resistance:042]: 'resistance_sensor' - Resistance 8232.2Ω
[17:24:57][D][sensor:093]: 'resistance_sensor': Sending state 8232.17578 Ω with 1 decimals of accuracy
[17:24:57][D][ntc:026]: 'Temperature' - Temperature: 29.4°C
[17:24:57][D][sensor:093]: 'Temperature': Sending state 29.44318 °C with 1 decimals of accuracy
[17:24:57][W][nextion:477]: Invalid variable name
[17:25:00][W][nextion:477]: Invalid variable name
[17:25:00][W][nextion:477]: Invalid variable name
[17:25:00][W][nextion:477]: Invalid variable name
[17:25:00][W][nextion:477]: Invalid variable name
[17:25:00][W][nextion:477]: Invalid variable name
[17:25:00][W][nextion:477]: Invalid variable name
[17:25:00][W][nextion:477]: Invalid variable name

### Home Assistant Logs

[home-assistant_2025-06-13T15-26-42.284Z.log](https://github.com/user-attachments/files/20729066/home-assistant_2025-06-13T15-26-42.284Z.log)

**Comment by OlegUaDp** [comment]
I had this problem too, the only way I got the panel back to life.
1: Installed firmware v4.3.13
2: Loaded "Blank.tft"
3: Loaded "nspanel_eu.tft" v4.3.13
4: Installed firmware v4.3.15
5: Updated blueprint v4.3.15
After DO NOT LOAD "nspanel_eu.tft"

**Comment by edwardtfn** [comment]
The problem is not with v4.3.15, but with ESPHome DEV. It was fixed last night, but I'm not sure it was included in the last build:

- esphome/esphome#9064

**Comment by Fynnmk** [comment]
Ok, and what do I do for now?

**Comment by edwardtfn** [comment]
Try adding this to your panel's Yaml:

```yaml
external_components:
  - source: github://pr#9064
    components:
      - nextion
```

Then flash your panel and then try a TFT transfer again.

But then, after updating your ESPHome builder in a couple of days, remember to remove those lines, as that will be part of ESPHome dev.

**Comment by Fynnmk** [comment]
Thx, I had added that, but it still does not work, at least wireless. Do I have to do it with the serial adapter?

**Comment by edwardtfn** [comment]
Look, I see in your logs that Nextion (the display) is responding at 115200bps:

```log
[17:24:40][C][uart.idf:165]: Baud Rate: 115200 baud
...
[17:24:41][C][nextion:149]: Nextion:
[17:24:41][C][nextion:153]: Device Model: NX4832F035_011C
[17:24:41][C][nextion:153]: FW Version: 110
[17:24:41][C][nextion:153]: Serial Number: 32B434018D47B237
[17:24:41][C][nextion:153]: Flash Size:   16777216
[17:24:41][C][nextion:161]: Wake On Touch: YES
[17:24:41][C][nextion:161]: Exit reparse: YES
...
[17:24:50][C][nspanel_ha_blueprint:2294]: UART:
[17:24:50][C][nspanel_ha_blueprint:2295]: Baud rate: 115200 bps
[17:24:50][C][nspanel_ha_blueprint:2296]: Queue size: 0
[17:24:50][C][nspanel_ha_blueprint:2300]: Nextion:
[17:24:50][C][nspanel_ha_blueprint:2301]: Queue size: 0
[17:24:50][C][nspanel_ha_blueprint:2303]: Is setup: True
[17:24:50][C][nspanel_ha_blueprint:2310]: Init: True
[17:24:50][W][nspanel_ha_blueprint:2314]: TFT: UNKNOWN
```

So, on your device's page, make sure you have both controls "**Baud rate**" and "**Update TFT display - Baud rate**" set to 115200bps. Please note that those controls may be hidden, so you will have to enable those:

![Image](https://github.com/user-attachments/assets/d3a1831d-99d9-4fbc-85b9-16525f46b566)
![Image](https://github.com/user-attachments/assets/3d0443c0-8d83-4920-ba91-fa48d73d3029)
![Image](https://github.com/user-attachments/assets/7b29094c-421b-439b-9441-b892e5cac32a)
![Image](https://github.com/user-attachments/assets/fd5e18f2-0a8e-49f1-892d-775ee6335dd4)
![Image](https://github.com/user-attachments/assets/dec4c3d8-31ba-4106-bdbf-112b63b35bb9)

Then, on "**Update TFT display - model**", please select "**NSPanel Blank**":
![Image](https://github.com/user-attachments/assets/0d9f7882-1b9f-4455-8b37-12997f1badac)

And then start collecting ESPHome logs, then press "**Update TFT display**":
![Image](https://github.com/user-attachments/assets/ee231cbd-5b28-4ecc-bb8b-df6f6fc83663)

Wait for the system trying a few times until it restarts. After the restart, please wait like 15sec and then save all the logs collected and share it here, please.

**Comment by Fynnmk** [comment]
[logs_nspanal_logs - uploead blank tft.txt](https://github.com/user-attachments/files/20736659/logs_nspanal_logs.-.uploead.blank.tft.txt)

![Image](https://github.com/user-attachments/assets/a51177be-387d-401b-9359-cf5246ff53d4)

The blank tft works fine, I think the Problem might be with the eu tft file.
Is this the right log you ask for?

**Comment by edwardtfn** [comment]
This is the right logs and as you have installed the blank TFT we know your display is not in reparse mode anymore.
What happens when you try to install the EU file?

**Comment by Fynnmk** [comment]
[logs_nspanal_logs - try install eu tft.txt](https://github.com/user-attachments/files/20736844/logs_nspanal_logs.-.try.install.eu.tft.txt)

There is "System data ERROR!" again


Maybe there is another problem
During the flash there is an orange message as well
[logs_nspanal_run nspalnel.yaml reflash.txt](https://github.com/user-attachments/files/20736861/logs_nspanal_run.nspalnel.yaml.reflash.txt)
I have installed the latest esp home build (there was written that the nextion problem was fixed) and removed the code you gave me yesterday

**Comment by sztupy** [comment]
I have the same issue wtih 4.4.0.dev10 and 2025.7.0.dev. I can get the blank one instaled, but anything larger I get the System Data ERROR. Tried a couple times now, including rolling back to Blank to force a full TFT install

**Comment by Fynnmk** [comment]
I don't know what I have done different, but suddenly is starts working just fine. Maybe just a new update from esphome

**Comment by edwardtfn** [comment]
We do had a fix on ESPHome DEV around this, so hopefully it should be working for everyone now if you have your system updated.

**Comment by sztupy** [comment]
> We do had a fix on ESPHome DEV around this, so hopefully it should be working for everyone now if you have your system updated.

unfortunately it is still broken for me with the latest DEV install. It does work with `2025.5.2` however

**Comment by edwardtfn** [comment]
What about v4.3.16 (still in `dev`)?

**Comment by sztupy** [comment]
I'll need to check. It definitely worked with 2025.5.2 and both 4.3.15 and 4.4.0.dev10. I'll test with 2025.7.0-dev and 4.3.16 soon

**Comment by PaulBiod** [comment]
> I had this problem too, the only way I got the panel back to life. 1: Installed firmware v4.3.13 2: Loaded "Blank.tft" 3: Loaded "nspanel_eu.tft" v4.3.13 4: Installed firmware v4.3.15 5: Updated blueprint v4.3.15 After DO NOT LOAD "nspanel_eu.tft"

Hi @OlegUaDp 
how to roll back to 4.3.13 the firmware ?
Thanks
