### ISSUE TITLE
`Bug` Boot: Waiting for Blueprint version despite update to v4.3.31

### ISSUE THREAD

**Issue by CD-Nitrox** [Blackymas/NSPanel_HA_Blueprint#2855]
### TFT Version

4.3.31

### Firmware Version

4.3.31

### Blueprint Version

3.3.31

### Panel Model

EU

### What is the bug?

The issue reported in v4.3.30 is persisting after the new update.

A single NSPanel remains on the Initializing screen with the message Boot: Waiting for Blueprint version
Two other panels on the same versions are working without issue.

<img width="735" height="722" alt="Image" src="https://github.com/user-attachments/assets/1101d243-da2f-4fe8-aadd-1c96fbfc1ce8" />

Notification received in HA

<img width="487" height="314" alt="Image" src="https://github.com/user-attachments/assets/d1c235ed-7bf6-454d-8feb-07e97e454a92" />

Missing values in HA device

<img width="369" height="391" alt="Image" src="https://github.com/user-attachments/assets/ba7d048e-8b2c-4313-bacf-a666165d7e8b" />

Install log:
> INFO ESPHome 2025.8.4
INFO Reading configuration /config/esphome/bureau-nspanel.yaml...
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Detected timezone 'Europe/Zurich'
INFO Generating C++ source...
INFO Compiling app...
Processing bureau-nspanel (board: esp32dev; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip)
--------------------------------------------------------------------------------
INFO Package configuration completed successfully
INFO Package configuration completed successfully
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50402.0 (5.4.2) 
 - tool-cmake @ 3.30.2 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.0.2 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp-elf @ 14.2.0+20241119
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 7.4.2
|-- noise-c @ 0.1.10
Compiling .pioenvs/bureau-nspanel/src/main.cpp.o
Linking .pioenvs/bureau-nspanel/firmware.elf
                            Memory Type Usage Summary                             
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Memory Type/Section ┃ Used [bytes] ┃ Used [%] ┃ Remain [bytes] ┃ Total [bytes] ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Flash Code          │      1054044 │          │                │               │
│    .text            │      1054044 │          │                │               │
│ Flash Data          │       189200 │          │                │               │
│    .rodata          │       188944 │          │                │               │
│    .appdesc         │          256 │          │                │               │
│ IRAM                │        97454 │    74.35 │          33618 │        131072 │
│    .text            │        96427 │    73.57 │                │               │
│    .vectors         │         1027 │     0.78 │                │               │
│ DRAM                │        31460 │    17.41 │         149276 │        180736 │
│    .data            │        16668 │     9.22 │                │               │
│    .bss             │        14792 │     8.18 │                │               │
│ SPI DRAM            │        12860 │     0.31 │        4181444 │       4194304 │
│    .bss             │        12860 │     0.31 │                │               │
└─────────────────────┴──────────────┴──────────┴────────────────┴───────────────┘
Total image size: 1357366 bytes (.bin may be padded larger)
Note: The reported total sizes may be smaller than those in the technical reference manual due to reserved memory and application configuration. The total flash size available for the application is not included by default, as it cannot be reliably determined due to the presence of other data like the bootloader, partition table, and application partition size.
RAM:   [=         ]   9.6% (used 31460 bytes from 327680 bytes)
Flash: [=======   ]  74.0% (used 1357110 bytes from 1835008 bytes)
Building .pioenvs/bureau-nspanel/firmware.bin
Warning: DEPRECATED: 'esptool.py' is deprecated. Please use 'esptool' instead. The '.py' suffix will be removed in a future major release.
Creating ESP32 image...
Successfully created ESP32 image.
merge_factory_bin([".pioenvs/bureau-nspanel/firmware.bin"], [".pioenvs/bureau-nspanel/firmware.elf"])
Info: bootloader.bin not found - skipping
Info: partition-table.bin not found - skipping
Info: ota_data_initial.bin not found - skipping
Info: bureau-nspanel.bin not found - skipping
Using FLASH_EXTRA_IMAGES from PlatformIO environment
Merging binaries into /data/build/bureau-nspanel/.pioenvs/bureau-nspanel/firmware.factory.bin
Merging binaries with esptool
SHA digest in image updated.
Wrote 0x15b6c0 bytes to file '/data/build/bureau-nspanel/.pioenvs/bureau-nspanel/firmware.factory.bin', ready to flash to offset 0x0.
Successfully created /data/build/bureau-nspanel/.pioenvs/bureau-nspanel/firmware.factory.bin
esp32_copy_ota_bin([".pioenvs/bureau-nspanel/firmware.bin"], [".pioenvs/bureau-nspanel/firmware.elf"])
Copied firmware to /data/build/bureau-nspanel/.pioenvs/bureau-nspanel/firmware.ota.bin
======================== [SUCCESS] Took 130.00 seconds ========================
INFO Successfully compiled program.
INFO Uploading to 192.168.1.130
INFO Connecting to 192.168.1.130 port 3232...
INFO Connected to 192.168.1.130
INFO Uploading /data/build/bureau-nspanel/.pioenvs/bureau-nspanel/firmware.bin (1357504 bytes)
Uploading: [============================================================] 100% Done...

INFO Upload took 6.77 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.1.130 using esphome API
INFO Successfully resolved bureau-nspanel @ 192.168.1.130 in 0.000s
INFO Successfully connected to bureau-nspanel @ 192.168.1.130 in 11.374s
INFO Successful handshake with bureau-nspanel @ 192.168.1.130 in 0.085s
[11:28:59][I][app:200]: ESPHome version 2025.8.4 compiled on Sep 14 2025, 11:26:31
[11:28:59][I][app:202]: Project Blackymas.NSPanel_HA_Blueprint version 4.3.31
[11:28:59][C][wifi:661]: WiFi:
[11:28:59][C][wifi:444]:   Local MAC: E2:65:B8:1D:3C:98
[11:28:59][C][wifi:449]:   SSID: [redacted]
[11:28:59][C][wifi:452]:   IP Address: 192.168.1.130
[11:28:59][C][wifi:456]:   BSSID: [redacted]
[11:28:59][C][wifi:456]:   Hostname: 'bureau-nspanel'
[11:28:59][C][wifi:456]:   Signal strength: -64 dB ▂▄▆█
[11:28:59][C][wifi:467]:   Channel: 11
[11:28:59][C][wifi:467]:   Subnet: 255.255.255.0
[11:28:59][C][wifi:467]:   Gateway: 192.168.1.1
[11:28:59][C][wifi:467]:   DNS1: 194.230.55.96
[11:28:59][C][wifi:467]:   DNS2: 212.98.37.130
[11:28:59][C][logger:252]: Logger:
[11:28:59][C][logger:252]:   Max Level: DEBUG
[11:28:59][C][logger:252]:   Initial Level: DEBUG
[11:28:59][C][logger:258]:   Log Baud Rate: 115200
[11:28:59][C][logger:258]:   Hardware UART: UART0
[11:28:59][C][logger:265]:   Task Log Buffer Size: 768
[11:28:59][C][uart.idf:153]: UART Bus 1:
[11:28:59][C][uart.idf:154]:   TX Pin: GPIO16
[11:28:59][C][uart.idf:155]:   RX Pin: GPIO17
[11:28:59][C][uart.idf:157]:   RX Buffer Size: 256
[11:28:59][C][uart.idf:159]:   Baud Rate: 115200 baud
[11:28:59][C][uart.idf:159]:   Data Bits: 8
[11:28:59][C][uart.idf:159]:   Parity: NONE
[11:28:59][C][uart.idf:159]:   Stop bits: 1
[11:28:59][C][template.binary_sensor:020]: Template Binary Sensor 'Nextion display'
[11:28:59][C][template.binary_sensor:020]:   Device Class: 'connectivity'
[11:28:59][C][template.binary_sensor:020]: Template Binary Sensor 'Notification Unread'
[11:28:59][C][template.number:050]: Template Number 'Display Brightness'
[11:28:59][C][template.number:050]:   Unit of Measurement: '%'
[11:28:59][C][template.number:051]:   Optimistic: YES
[11:28:59][C][template.number:052]:   Update Interval: 60.0s
[11:28:59][C][template.number:050]: Template Number 'Display Brightness Dimdown'
[11:28:59][C][template.number:050]:   Unit of Measurement: '%'
[11:28:59][C][template.number:051]:   Optimistic: YES
[11:28:59][C][template.number:052]:   Update Interval: 60.0s
[11:28:59][C][template.number:050]: Template Number 'Display Brightness Sleep'
[11:28:59][C][template.number:050]:   Unit of Measurement: '%'
[11:28:59][C][template.number:051]:   Optimistic: YES
[11:28:59][C][template.number:052]:   Update Interval: 60.0s
[11:28:59][C][template.number:050]: Template Number 'Timeout Sleep'
[11:28:59][C][template.number:050]:   Icon: 'mdi:timer'
[11:28:59][C][template.number:050]:   Unit of Measurement: 's'
[11:28:59][C][template.number:051]:   Optimistic: YES
[11:28:59][C][template.number:052]:   Update Interval: 60.0s
[11:28:59][C][template.number:050]: Template Number 'Timeout Page'
[11:28:59][C][template.number:050]:   Icon: 'mdi:timer'
[11:28:59][C][template.number:050]:   Unit of Measurement: 's'
[11:28:59][C][template.number:051]:   Optimistic: YES
[11:28:59][C][template.number:052]:   Update Interval: 60.0s
[11:28:59][C][template.number:050]: Template Number 'Timeout Dimming'
[11:28:59][C][template.number:050]:   Icon: 'mdi:timer'
[11:28:59][C][template.number:050]:   Unit of Measurement: 's'
[11:28:59][C][template.number:051]:   Optimistic: YES
[11:28:59][C][template.number:052]:   Update Interval: 60.0s
[11:29:00][C][template.number:050]: Template Number 'Sound - Volume'
[11:29:00][C][template.number:050]:   Unit of Measurement: '%'
[11:29:00][C][template.number:050]:   Device Class: 'sound_pressure'
[11:29:00][C][template.number:051]:   Optimistic: YES
[11:29:00][C][template.number:052]:   Update Interval: 60.0s
[11:29:00][C][template.number:050]: Template Number 'Temperature Correction'
[11:29:00][C][template.number:050]:   Unit of Measurement: '°C'
[11:29:00][C][template.number:051]:   Optimistic: YES
[11:29:00][C][template.number:052]:   Update Interval: 60.0s
[11:29:00][C][template.select:064]: Template Select 'Baud rate'
[11:29:00][C][template.select:064]:   Icon: 'mdi:swap-horizontal'
[11:29:00][C][template.select:065]:   Update Interval: 60.0s
[11:29:00][C][template.select:068]:   Optimistic: YES
[11:29:00][C][template.select:068]:   Initial Option: 115200
[11:29:00][C][template.select:068]:   Restore Value: YES
[11:29:00][C][template.select:064]: Template Select 'Wake-up page'
[11:29:00][C][template.select:064]:   Icon: 'mdi:page-next-outline'
[11:29:00][C][template.select:065]:   Update Interval: 60.0s
[11:29:00][C][template.select:068]:   Optimistic: YES
[11:29:00][C][template.select:068]:   Initial Option: home
[11:29:00][C][template.select:068]:   Restore Value: YES
[11:29:00][C][template.select:064]: Template Select 'Update TFT display - Model'
[11:29:00][C][template.select:064]:   Icon: 'mdi:file-sync'
[11:29:00][C][template.select:065]:   Update Interval: 60.0s
[11:29:00][C][template.select:068]:   Optimistic: YES
[11:29:00][C][template.select:068]:   Initial Option: NSPanel EU
[11:29:00][C][template.select:068]:   Restore Value: YES
[11:29:00][C][template.select:064]: Template Select 'Update TFT display - Baud rate'
[11:29:00][C][template.select:064]:   Icon: 'mdi:swap-horizontal'
[11:29:00][C][template.select:065]:   Update Interval: 60.0s
[11:29:00][C][template.select:068]:   Optimistic: YES
[11:29:00][C][template.select:068]:   Initial Option: 921600
[11:29:00][C][template.select:068]:   Restore Value: YES
[11:29:00][C][switch.gpio:087]: GPIO Switch 'Nextion display - Power'
[11:29:00][C][switch.gpio:087]:   Restore Mode: always ON
[11:29:00][C][switch.gpio:029]:   Pin: GPIO4
[11:29:00][C][template.text_sensor:020]: Template Sensor 'Current Page'
[11:29:00][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[11:29:00][C][template.text_sensor:020]: Template Sensor 'Detailed Entity'
[11:29:00][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[11:29:00][C][template.text_sensor:020]: Template Sensor 'Version TFT'
[11:29:00][C][template.text_sensor:020]:   Icon: 'mdi:tag-text-outline'
[11:29:00][C][template.text_sensor:020]: Template Sensor 'Device Name'
[11:29:00][C][template.text_sensor:020]:   Icon: 'mdi:identifier'
[11:29:00][C][template.text_sensor:020]: Template Sensor 'Version Blueprint'
[11:29:00][C][template.text_sensor:020]:   Icon: 'mdi:tag-text-outline'
[11:29:00][C][template.text_sensor:020]: Template Sensor 'Version ESPHome'
[11:29:00][C][template.text_sensor:020]:   Icon: 'mdi:tag-text-outline'
[11:29:00][C][template.text_sensor:020]: Template Sensor 'Notification Label'
[11:29:00][C][template.text_sensor:020]:   Icon: 'mdi:bell-outline'
[11:29:00][C][ledc.output:150]: Output:
[11:29:00][C][ledc.output:151]:   Pin GPIO21
[11:29:00][C][ledc.output:152]:   Channel: 0
[11:29:00][C][ledc.output:152]:   PWM Frequency: 1000.0 Hz
[11:29:00][C][ledc.output:152]:   Phase angle: 0.0°
[11:29:00][C][ledc.output:152]:   Bit depth: 16
[11:29:00][C][gpio.binary_sensor:052]: GPIO Binary Sensor 'Left Button'
[11:29:00][C][gpio.binary_sensor:053]:   Pin: GPIO14
[11:29:00][C][gpio.binary_sensor:055]:   Mode: interrupt
[11:29:00][C][gpio.binary_sensor:072]:   Interrupt Type: ANY_EDGE
[11:29:00][C][gpio.binary_sensor:052]: GPIO Binary Sensor 'Right Button'
[11:29:00][C][gpio.binary_sensor:053]:   Pin: GPIO27
[11:29:00][C][gpio.binary_sensor:055]:   Mode: interrupt
[11:29:00][C][gpio.binary_sensor:072]:   Interrupt Type: ANY_EDGE
[11:29:00][C][switch.gpio:087]: GPIO Switch 'Relay 1'
[11:29:00][C][switch.gpio:087]:   Restore Mode: restore defaults to OFF
[11:29:00][C][switch.gpio:029]:   Pin: GPIO22
[11:29:00][C][switch.gpio:087]: GPIO Switch 'Relay 2'
[11:29:00][C][switch.gpio:087]:   Restore Mode: restore defaults to OFF
[11:29:00][C][switch.gpio:029]:   Pin: GPIO19
[11:29:00][C][template.text_sensor:020]: Template Sensor 'Notification Text'
[11:29:00][C][template.text_sensor:020]:   Icon: 'mdi:message-text-outline'
[11:29:01][C][template.switch:087]: Template Switch 'Update TFT automatically'
[11:29:01][C][template.switch:087]:   Restore Mode: restore defaults to OFF
[11:29:01][C][template.switch:095]:   Icon: 'mdi:file-sync'
[11:29:01][C][template.switch:057]:   Optimistic: YES
[11:29:01][C][template.switch:087]: Template Switch 'Sound - Notification'
[11:29:01][C][template.switch:087]:   Restore Mode: restore defaults to OFF
[11:29:01][C][template.switch:057]:   Optimistic: YES
[11:29:01][C][restart.button:017]: Restart Button 'Restart'
[11:29:01][C][restart.button:017]:   Icon: 'mdi:restart'
[11:29:01][C][homeassistant.time:010]: Home Assistant Time:
[11:29:01][C][homeassistant.time:010]:   Timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
[11:29:01][C][adc.esp32:121]: ADC Sensor 'ntc_source'
[11:29:01][C][adc.esp32:121]:   State Class: 'measurement'
[11:29:01][C][adc.esp32:121]:   Unit of Measurement: 'V'
[11:29:01][C][adc.esp32:121]:   Accuracy Decimals: 2
[11:29:01][C][adc.esp32:121]:   Device Class: 'voltage'
[11:29:01][C][adc.esp32:122]:   Pin: GPIO38
[11:29:01][C][adc.esp32:123]:   Channel:       2
[11:29:01][C][adc.esp32:123]:   Unit:          ADC1
[11:29:01][C][adc.esp32:123]:   Attenuation:   12 dB
[11:29:01][C][adc.esp32:123]:   Samples:       4
[11:29:01][C][adc.esp32:123]:   Sampling mode: average
[11:29:01][C][adc.esp32:133]:   Setup Status:
[11:29:01][C][adc.esp32:133]:     Handle Init:  OK
[11:29:01][C][adc.esp32:133]:     Config:       OK
[11:29:01][C][adc.esp32:133]:     Calibration:  OK
[11:29:01][C][adc.esp32:133]:     Overall Init: OK
[11:29:01][C][adc.esp32:143]:   Update Interval: 60.0s
[11:29:01][C][resistance:010]: Resistance Sensor 'resistance_sensor'
[11:29:01][C][resistance:010]:   State Class: 'measurement'
[11:29:01][C][resistance:010]:   Unit of Measurement: 'Ω'
[11:29:01][C][resistance:010]:   Accuracy Decimals: 1
[11:29:01][C][resistance:010]:   Icon: 'mdi:flash'
[11:29:01][C][resistance:011]:   Configuration: DOWNSTREAM
[11:29:01][C][resistance:011]:   Resistor: 11200.00Ω
[11:29:01][C][resistance:011]:   Reference Voltage: 3.3V
[11:29:01][C][ntc:014]: NTC Sensor 'Temperature'
[11:29:01][C][ntc:014]:   State Class: 'measurement'
[11:29:01][C][ntc:014]:   Unit of Measurement: '°C'
[11:29:01][C][ntc:014]:   Accuracy Decimals: 1
[11:29:01][C][ntc:014]:   Device Class: 'temperature'
[11:29:01][C][psram:016]: PSRAM:
[11:29:01][C][psram:019]:   Available: YES
[11:29:01][C][psram:021]:   Size: 2048 KB
[11:29:01][C][rtttl:030]: Rtttl:
[11:29:01][C][rtttl:030]:   Gain: 0.600000
[11:29:01][C][nextion:147]: Nextion:
[11:29:01][C][nextion:152]:   Exit reparse:   YES
[11:29:01][C][nextion:152]:   Wake On Touch:  YES
[11:29:01][C][nextion:152]:   Touch Timeout:  0
[11:29:01][C][nextion:181]:   Start Up Page:  0
[11:29:02][C][esphome.ota:075]: Over-The-Air updates:
[11:29:02][C][esphome.ota:075]:   Address: bureau-nspanel.local:3232
[11:29:02][C][esphome.ota:075]:   Version: 2
[11:29:02][C][esphome.ota:082]:   Password configured
[11:29:02][C][safe_mode:018]: Safe Mode:
[11:29:02][C][safe_mode:019]:   Boot considered successful after 60 seconds
[11:29:02][C][safe_mode:019]:   Invoke after 10 boot attempts
[11:29:02][C][safe_mode:019]:   Remain for 300 seconds
[11:29:02][C][api:205]: Server:
[11:29:02][C][api:205]:   Address: bureau-nspanel.local:6053
[11:29:02][C][api:210]:   Noise encryption: YES
[11:29:02][C][mdns:124]: mDNS:
[11:29:02][C][mdns:124]:   Hostname: bureau-nspanel
[11:29:03][D][nextion:337]: Manual ready set
[11:29:03][I][nspanel.hw.display:056]: Nextion setup triggered
[11:29:03][D][binary_sensor:026]: 'Nextion display': New state is ON
[11:29:03][D][nspanel.base:112]: The watchdog is starting a round
[11:29:03][E][nextion:369]: Queue empty
[11:29:03][D][nextion:562]: New page: 0
[11:29:03][I][nspanel.hw.display:063]: Page changed: 'boot'->'boot'
[11:29:03][W][nspanel.hw.display:064]: Same page
[11:29:03][D][text_sensor:069]: 'Current Page': Sending state 'boot'
[11:29:03][D][text_sensor:069]: 'Detailed Entity': Sending state ''
[11:29:03][D][binary_sensor:026]: 'Nextion display': New state is OFF
[11:29:03][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:03][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[11:29:03][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[11:29:03][D][main:139]: Page boot called
[11:29:03][W][script:060]: Script 'page_boot_exit_on_timeout' is already running! (mode: single)
[11:29:03][D][nspanel.page.boot:053]: Page boot constructor started
[11:29:03][D][nspanel.page.boot:066]: Page boot constructor completed
[11:29:04][D][text_sensor:069]: 'NSPanel local event': Sending state '{"page": "boot", "event": "params", "display_mode": 1, "charset": 1, "version": "4.3.31"}'
[11:29:04][D][text_sensor:069]: 'Version TFT': Sending state '4.3.31'
[11:29:04][D][nspanel.core:294]: Device not ready for tasks - Skip version check
[11:29:04][I][nspanel.hw.display:218]: Display params:
[11:29:04][I][nspanel.hw.display:219]:   Mode:        1
[11:29:04][I][nspanel.hw.display:220]:   Charset:     1
[11:29:04][I][nspanel.hw.display:221]:   TFT version: v4.3.31
[11:29:04][D][nextion_textsensor:014]: Text sensor: localevent='{"page": "boot", "event": "params", "display_mode": 1, "charset": 1, "version": "4.3.31"}'
[11:29:04][D][nextion:562]: New page: 0
[11:29:04][I][nspanel.hw.display:063]: Page changed: 'boot'->'boot'
[11:29:04][W][nspanel.hw.display:064]: Same page
[11:29:04][D][text_sensor:069]: 'Current Page': Sending state 'boot'
[11:29:04][D][text_sensor:069]: 'Detailed Entity': Sending state ''
[11:29:04][W][component:423]: display took a long time for an operation (89 ms)
[11:29:04][W][component:424]: Components should block for at most 30 ms
[11:29:04][I][TAG_BOOT:033]: Starting boot sequence
[11:29:04][W][script:060]: Script 'wait_to_be_ready' is already running! (mode: single)
[11:29:04][I][TAG_BOOT:346]: Starting boot preparation sequence
[11:29:04][W][script:060]: Script 'page_boot_exit_on_timeout' is already running! (mode: single)
[11:29:04][I][TAG_BOOT:281]: Starting boot critical components sequence
[11:29:04][I][TAG_BOOT:287]: Starting boot early routines sequence
[11:29:04][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[11:29:04][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[11:29:04][D][main:139]: Page boot called
[11:29:04][W][script:060]: Script 'page_boot_exit_on_timeout' is already running! (mode: single)
[11:29:04][D][nspanel.page.boot:053]: Page boot constructor started
[11:29:04][D][nspanel.page.boot:066]: Page boot constructor completed
[11:29:05][D][nspanel.boot:338]: Boot: Starting sequence
[11:29:05][D][script.boot_progress:363]: Progress: 0.0%
[11:29:05][D][script.boot_progress:363]: Progress: 0.0%
[11:29:05][D][script.boot_progress:363]: Progress: 0.0%
[11:29:05][D][nspanel.boot:338]: Boot: Waiting for Wi-Fi
[11:29:05][D][nspanel.boot:338]: Boot: Wi-Fi connected
[11:29:05][D][script.boot_progress:363]: Progress: 0.0%
[11:29:05][D][nspanel.boot:338]: Boot: API connected
[11:29:05][D][script.boot_progress:363]: Progress: 0.0%
[11:29:05][D][nspanel.boot:338]: Boot: Sending display settings
[11:29:05][D][script.boot_progress:363]: Progress: 0.0%
[11:29:05][D][nspanel.boot:338]: Boot: Publish Nextion state
[11:29:05][D][binary_sensor:026]: 'Nextion display': New state is ON
[11:29:05][D][binary_sensor:026]: 'Nextion display': New state is OFF
[11:29:05][D][nspanel.boot:338]: Boot: Send `nextion_init` event to Home Assistant
[11:29:05][D][script.boot_progress:363]: Progress: 0.0%
[11:29:05][D][nspanel.boot:299]: Asking Blueprint to start sending data
[11:29:05][D][nspanel.boot:312]: Give some time for the blueprint to respond
[11:29:05][D][nspanel.boot:338]: Boot: Waiting for Blueprint
[11:29:05][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:06][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:07][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:08][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:08][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:09][D][nspanel.boot:338]: Boot: Check TFT version
[11:29:09][C][nspanel.hw.display:151]: UART:
[11:29:09][C][nspanel.hw.display:152]:   Baud rate:   115200 bps
[11:29:09][C][nspanel.hw.display:153]:   Queue size:  0
[11:29:09][C][nspanel.hw.display:157]: Nextion:
[11:29:09][C][nspanel.hw.display:158]:   Queue size:  0
[11:29:09][C][nspanel.hw.display:160]:   Is setup:    True
[11:29:09][W][nspanel.hw.display:169]:   Init:        False
[11:29:09][C][nspanel.hw.display:173]:   TFT:         4.3.31
[11:29:09][C][nspanel.hw.display:177]: Wake-up page: home
[11:29:09][C][nspanel.hw.wifi:056]: WiFi: Connected (1.760221% dBm)
[11:29:09][C][nspanel.core:344]: Blueprint:
[11:29:09][W][nspanel.core:349]:   Progress: 0.0%
[11:29:09][W][nspanel.core:350]:   State: Pending
[11:29:09][C][nspanel.core:353]: Requesting blueprint settings
[11:29:09][D][script:077]: Script 'boot_event' restarting (mode: restart)
[11:29:09][D][nspanel.boot:312]: Give some time for the blueprint to respond
[11:29:09][C][nspanel.core:359]: ESPHome:
[11:29:09][C][nspanel.core:360]:   Version: 4.3.31
[11:29:09][C][nspanel.core:361]:   Compiler: 2025.8.4
[11:29:09][C][nspanel.core:362]:   Compilation time: Sep 14 2025, 11:26:31
[11:29:09][C][nspanel.core:366]:   Framework:   ESP-IDF
[11:29:09][C][nspanel.core:381]:   Free heap:
[11:29:09][C][nspanel.core:384]:     Internal:   121020 bytes (36.2%)
[11:29:09][C][nspanel.core:394]:     PSRAM:     2009596 bytes (96.4%)
[11:29:09][C][nspanel.core:403]: Packages:
[11:29:09][C][nspanel.core:405]:   - Core
[11:29:09][C][nspanel.core:414]:   - Upload TFT
[11:29:09][C][nspanel.api:654]: API: Connected
[11:29:09][C][nspanel.addon.upload_tft:097]: Add-on Upload TFT:
[11:29:09][C][nspanel.addon.upload_tft:098]:   File model: NSPanel EU
[11:29:09][C][nspanel.addon.upload_tft:099]:   Valid TFT:  YES
[11:29:09][W][component:423]: script took a long time for an operation (151 ms)
[11:29:09][W][component:424]: Components should block for at most 30 ms
[11:29:09][W][component:423]: api took a long time for an operation (160 ms)
[11:29:09][W][component:424]: Components should block for at most 30 ms
[11:29:09][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:10][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:29:10][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:11][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:12][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:13][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:13][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:14][D][script:077]: Script 'watchdog_round' restarting (mode: restart)
[11:29:14][D][nspanel.base:112]: The watchdog is starting a round
[11:29:14][W][script:060]: Script 'watchdog_round_wait_to_end' is already running! (mode: single)
[11:29:14][D][nspanel.base:120]: The watchdog completed the round
[11:29:14][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:15][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:29:15][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:16][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:17][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:18][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:18][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:19][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:20][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:29:20][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:21][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:22][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:23][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:24][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:25][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:25][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:29:25][W][nspanel.hw.display:278]: Device is not ready for changing page
[11:29:26][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:27][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:28][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:28][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:29][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:30][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:30][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:29:31][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:32][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:33][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:33][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:34][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:35][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:35][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:29:36][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:37][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:38][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:38][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:39][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:39][W][nspanel.boot:319]: Inform Blueprint that no data was received yet
[11:29:39][D][nspanel.boot:312]: Give some time for the blueprint to respond
[11:29:40][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:40][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:29:41][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:42][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:43][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:43][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:44][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:45][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:45][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:29:46][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:47][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:48][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:48][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:49][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:50][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:50][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:29:51][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:52][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:52][I][safe_mode:042]: Boot seems successful; resetting boot loop counter
[11:29:52][D][esp32.preferences:142]: Writing 1 items: 0 cached, 1 written, 0 failed
[11:29:53][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:53][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:54][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:54][D][sensor:103]: 'ntc_source': Sending state 1.63300 V with 2 decimals of accuracy
[11:29:54][D][resistance:042]: 'resistance_sensor' - Resistance 10971.6Ω
[11:29:54][D][sensor:103]: 'resistance_sensor': Sending state 10971.56641 Ω with 1 decimals of accuracy
[11:29:54][D][ntc:026]: 'Temperature' - Temperature: 22.9°C
[11:29:54][D][sensor:103]: 'Temperature': Sending state 22.92782 °C with 1 decimals of accuracy
[11:29:54][W][script:060]: Script 'wait_to_be_ready' is already running! (mode: single)
[11:29:55][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:55][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:29:56][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:57][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:58][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:29:58][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:29:59][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:00][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:00][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:30:01][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:02][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:03][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:30:03][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:04][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:05][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:05][D][nspanel.boot:338]: Boot: Waiting for Blueprint version...
[11:30:06][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:07][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:08][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:30:08][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:09][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:09][D][nspanel.core:301]: Versions:
[11:30:09][D][nspanel.core:302]:   Blueprint: 
[11:30:09][D][nspanel.core:303]:   ESPHome:   4.3.31
[11:30:09][D][nspanel.core:304]:   TFT:       4.3.31
**[11:30:09][E][nspanel.core:314]: Blueprint version mismatch!**
[11:30:09][W][nspanel.boot:319]: Inform Blueprint that no data was received yet
[11:30:09][D][nspanel.boot:312]: Give some time for the blueprint to respond
[11:30:10][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:10][D][nspanel.core:337]: Check version completed
[11:30:11][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:12][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:13][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:30:13][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:14][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:15][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:16][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:17][D][nspanel.core:839]: Blueprint progress: 0.0%
[11:30:18][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[11:30:18][D][nspanel.core:839]: Blueprint progress: 0.0%

> 

### Your Panel's YAML

```yaml

```

### ESPHome Logs

```text

```

### Home Assistant Logs

```text

```

**Comment by CD-Nitrox** [comment]
I tried deleting the pre-existing blueprint automation and recreating a clean and simple one to see if it had anything to do with selected entities and actions, but no difference.

**Comment by Widgee9** [comment]
Same for me

**Comment by Jutsch** [comment]
same for me:
[13:04:12][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[13:04:13][I][TAG_BOOT:033]: Starting boot sequence
[13:04:13][W][script:060]: Script 'wait_to_be_ready' is already running! (mode: single)
[13:04:13][I][TAG_BOOT:346]: Starting boot preparation sequence
[13:04:13][I][TAG_BOOT:281]: Starting boot critical components sequence
[13:04:13][I][TAG_BOOT:287]: Starting boot early routines sequence
[13:04:14][D][nspanel.boot:338]: Boot: Starting sequence
[13:04:14][D][script.boot_progress:363]: Progress: 0.0%
[13:04:14][D][script.boot_progress:363]: Progress: 0.0%
[13:04:14][D][script.boot_progress:363]: Progress: 0.0%
[13:04:14][D][nspanel.boot:338]: Boot: Waiting for Wi-Fi
[13:04:14][D][nspanel.boot:338]: Boot: Wi-Fi connected
[13:04:14][D][script.boot_progress:363]: Progress: 0.0%
[13:04:14][D][nspanel.boot:338]: Boot: API connected
[13:04:14][D][script.boot_progress:363]: Progress: 0.0%
[13:04:14][D][nspanel.boot:338]: Boot: Sending display settings
[13:04:15][D][script.boot_progress:363]: Progress: 0.0%
[13:04:15][D][nspanel.boot:338]: Boot: Publish Nextion state
[13:04:15][D][binary_sensor:026]: 'Nextion display': New state is ON
[13:04:15][D][binary_sensor:026]: 'Nextion display': New state is OFF
[13:04:15][D][nspanel.boot:338]: Boot: Send `nextion_init` event to Home Assistant
[13:04:15][D][script.boot_progress:363]: Progress: 0.0%
[13:04:15][D][nspanel.boot:299]: Asking Blueprint to start sending data
[13:04:15][D][nspanel.boot:312]: Give some time for the blueprint to respond
[13:04:15][D][nspanel.boot:338]: Boot: Waiting for Blueprint
[13:04:15][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:16][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:17][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:17][D][nspanel.hw.display:530]: Fallback to page Home
[13:04:17][W][nspanel.hw.display:278]: Device is not ready for changing page
[13:04:17][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[13:04:18][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:19][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:19][C][nspanel.hw.display:151]: UART:
[13:04:19][C][nspanel.hw.display:152]:   Baud rate:   115200 bps
[13:04:19][C][nspanel.hw.display:153]:   Queue size:  0
[13:04:19][C][nspanel.hw.display:157]: Nextion:
[13:04:19][C][nspanel.hw.display:158]:   Queue size:  0
[13:04:19][C][nspanel.hw.display:160]:   Is setup:    True
[13:04:19][W][nspanel.hw.display:169]:   Init:        False
[13:04:19][W][nspanel.hw.display:171]:   TFT:         UNKNOWN
[13:04:19][C][nspanel.hw.display:177]: Wake-up page: home
[13:04:19][C][nspanel.hw.wifi:056]: WiFi: Connected (1.760213% dBm)
[13:04:19][C][nspanel.core:344]: Blueprint:
[13:04:19][W][nspanel.core:349]:   Progress: 0.0%
[13:04:19][W][nspanel.core:350]:   State: Pending
[13:04:19][C][nspanel.core:353]: Requesting blueprint settings
[13:04:19][D][script:077]: Script 'boot_event' restarting (mode: restart)
[13:04:19][D][nspanel.boot:312]: Give some time for the blueprint to respond
[13:04:19][C][nspanel.core:359]: ESPHome:
[13:04:19][C][nspanel.core:360]:   Version: 4.3.31
[13:04:19][C][nspanel.core:361]:   Compiler: 2025.8.4
[13:04:19][C][nspanel.core:362]:   Compilation time: Sep 14 2025, 13:01:49
[13:04:19][C][nspanel.core:366]:   Framework:   ESP-IDF
[13:04:19][C][nspanel.core:381]:   Free heap:
[13:04:19][C][nspanel.core:384]:     Internal:   124956 bytes (37.4%)
[13:04:19][C][nspanel.core:394]:     PSRAM:     2009456 bytes (96.4%)
[13:04:19][C][nspanel.core:403]: Packages:
[13:04:19][C][nspanel.core:405]:   - Core
[13:04:19][C][nspanel.core:414]:   - Upload TFT
[13:04:19][C][nspanel.core:435]: Components:
[13:04:19][C][nspanel.core:446]:   - Captive portal
[13:04:19][C][nspanel.api:654]: API: Connected
[13:04:19][C][nspanel.addon.upload_tft:097]: Add-on Upload TFT:
[13:04:19][C][nspanel.addon.upload_tft:098]:   File model: NSPanel EU
[13:04:19][C][nspanel.addon.upload_tft:099]:   Valid TFT:  NO
[13:04:19][W][component:423]: script took a long time for an operation (145 ms)
[13:04:19][W][component:424]: Components should block for at most 30 ms
[13:04:19][W][component:423]: api took a long time for an operation (153 ms)
[13:04:19][W][component:424]: Components should block for at most 30 ms
[13:04:20][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:21][D][script:077]: Script 'watchdog_round' restarting (mode: restart)
[13:04:21][D][nspanel.base:112]: The watchdog is starting a round
[13:04:21][W][script:060]: Script 'watchdog_round_wait_to_end' is already running! (mode: single)
[13:04:21][D][nspanel.base:120]: The watchdog completed the round
[13:04:21][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:22][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:22][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[13:04:23][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:24][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:25][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:26][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:27][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:27][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[13:04:28][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:29][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:30][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:31][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:32][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:32][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[13:04:33][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:34][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:35][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:36][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:37][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:37][W][nspanel.base:103]: Waiting for the system to be ready before executing an action
[13:04:38][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:39][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:40][D][nspanel.core:839]: Blueprint progress: 0.0%
[13:04:41][D][nspanel.core:839]: Blueprint progress: 0.0%

clean install on blueprint Version: v4.3.31

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.3.31 (or ref: main)

**Comment by Xitro01** [comment]
Here as well, tried to update to fix the button not being highlighted while on.
Fixed it by just cleaning build files and do another install.

**Comment by CD-Nitrox** [comment]
Tried another build file cleaning and update to v4.3.32. 
Still the same issue.

**Comment by Xitro01** [comment]
> Tried another build file cleaning and update to v4.3.32. Still the same issue.

Try it again after reimporting your blueprint. My blueprint is 1 version ahead of the rest, so that might be what solved it for me.

**Comment by CD-Nitrox** [comment]
I got a new error message after rebuilding the blueprint. 
Looking at another reported issue I strongly suspect I might have some discrepancies in entities and device IDs.

![Image](https://github.com/user-attachments/assets/682554a2-ffb8-4af2-a76b-920fd1f5278e)

I normally go for [device type - room] as a naming convention and for some reason inverted this the first time I setup that particular NSPanel. I only made the corrections in the display/friendly name, but somewhere it must have impacted entity IDs as well as I see that the entity called out in the error message doesn't match the one defined in the config yaml. (bureau_nspanel vs nspanel_bureau in the error) I will do a complete clean reinstall with the correct naming convention later today and see if it fixes the issues.

**Comment by CD-Nitrox** [comment]
Finally fixed the issue!

I aligned the device name with the friendly name, and ensured it was also consistent in the ESP Home integration screen. 

1. First removed the device and blueprint automation
2. Corrected the config yaml
3. Reinstalled through serial
4. Added the device back in the ESP Home integration in HA (autodetected) 
5. Finally added the blueprint again. 

@edwardtfn I am not sure if it is through my subsequent correction of the friendly name in either the config file and/or in the ESP Home display that the mismatch was introduced, or if there are some entities that are generating their name based on the friendly name instead of the device name but you might want to add a note about this in the resolution possibilities for missing blueprints?
