### ISSUE TITLE
`Bug` Swiping not possible anymore

### ISSUE THREAD

**Issue by Bascht74** [Blackymas/NSPanel_HA_Blueprint#2891]
### TFT Version

4.3.33

### Firmware Version

4.3.33

### Blueprint Version

4.3.33

### Panel Model

EU

### What is the bug?

If I try to swipe, it doesn't work anymore. I reflashed the firmware (first: blank, second: EU landscape), no change.

### Steps to Reproduce

1. boot panel
2. activate display
3. swipe from left to right or right to left

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "panel_eg_wohnzimmer"
  friendly_name: "Panel EG Wohnzimmer"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  mac_temp: "A4:C1:38:A8:E4:99"
  cover_entity: "cover.rollo_eg_wohnzimmer_terrasse_cover_s"
  boot_sound: false

  ##### addon-configuration #####
  ## addon_climate ##
  heater_relay: "1"
  temp_min: "15"
  temp_max: "25"
  temp_step: "0.5"
  heat_deadband: "0.3"  # Temperature delta before engaging heat
  heat_overrun: "0.2"   # Temperature delta before disengaging heat
  min_off_time: "30"
  min_run_time: "60"
  min_idle_time: "5"

# Customization area
##### My customization - Start #####
api:
  encryption: 
    key: !secret encryption_key
  reboot_timeout: 15min

ota:
  password: !secret ota_password
  platform: esphome

script:
  - id: !extend button_left_press_short
    then:
      - homeassistant.service:
          action: script.cover_stop_open
          data:
            cover_entity: '$cover_entity'
            panel_entity: '$device_name'
  - id: !extend button_right_press_short
    then:
      - homeassistant.service:
          action: script.cover_stop_close
          data:
            cover_entity: '$cover_entity'
            panel_entity: '$device_name'
  - id: !extend button_left_press_long
    then:
      - homeassistant.service:
          action: script.cover_set_cover_position
          data:
            position: '10'
            entity_id: '$cover_entity'
            panel_entity: '$device_name'   
  - id: !extend button_right_press_long 
    then:
      - homeassistant.service:
          action: script.cover_set_cover_position
          data:
            position: '50'
            entity_id: '$cover_entity'
            panel_entity: '$device_name'

time:
  - id: !extend time_provider
    on_time:
      - seconds: 00
        minutes: 00
        hours: 06
        then:
          - if:
             condition:
               lambda: true; // 'return id(thermostat_embedded).preset != CLIMATE_PRESET_AWAY;'
             then:
#               - climate.control:
#                   id: thermostat_embedded
#                   target_temperature: 23
      - seconds: 00
        minutes: 00
        hours: 00
        then:
          - if:
             condition:
               lambda: true; // 'return id(thermostat_embedded).preset != CLIMATE_PRESET_AWAY;'
             then:
#               - climate.control:
#                   id: thermostat_embedded
#                   target_temperature: 21

#climate:
#  - id: !extend thermostat_embedded
#    sensor: combined_temperature
#    preset:
#      - name: "home"
#        default_target_temperature_low: 22
#      - name: "away"
#        default_target_temperature_low: 17   
#    default_preset: home

#esp32_ble_tracker:
#  id: ble_tracker
#  scan_parameters:
#    window: 60ms
#    active: false

sensor:
 - id: combined_temperature
   platform: template
   internal: true
   lambda: |-
     if (wifi_component->is_connected() and api_server->is_connected()) {
       return temp_nspanel->state; // ext_temperature
     } else {
       return temp_nspanel->state;
     }
#  - platform: pvvx_mithermometer
#    mac_address: $mac_temp
#    temperature:
#      name: "Temperatur"
#      id: ext_temperature
#      device_class: temperature
#      filters:
#        - throttle_average: 120s
#    humidity:
#      name: "Luftfeuchtigkeit"
#      id: ext_humidity
#      device_class: humidity
#      filters:
#        - throttle_average: 120s
#    battery_level:
#      name: "Batterieladestand"
#      id: ext_battery_level
#      entity_category: diagnostic
#      filters:
#        - throttle_average: 3600s

#### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 0s
    files:
      - nspanel_esphome.yaml # Basic package
#      - esphome/nspanel_esphome_addon_climate_heat.yaml
```

### ESPHome Logs

```text
23:21:57.096][D][nextion:562]: New page: 1
[23:21:57.100][I][nspanel.hw.display:063]: Page changed: 'boot'->'home'
[23:21:57.105][D][text_sensor:069]: 'Current Page': Sending state 'home'
[23:21:57.109][D][text_sensor:069]: 'Detailed Entity': Sending state ''
[23:21:57.144][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:21:57.149][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:21:57.269][W][nextion:504]: Invalid variable name
[23:21:57.274][D][nextion:562]: New page: 1
[23:21:57.279][I][nspanel.hw.display:063]: Page changed: 'home'->'home'
[23:21:57.283][W][nspanel.hw.display:064]: Same page
[23:21:57.289][D][text_sensor:069]: 'Current Page': Sending state 'home'
[23:21:57.297][D][text_sensor:069]: 'Detailed Entity': Sending state ''
[23:21:57.329][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:21:57.336][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:21:57.417][D][script:088]: Script 'refresh_hardware_buttons_bars_with_delay' restarting (mode: restart)
[23:21:59.503][D][main:138]: Temperature correction changed.
[23:22:00.509][D][sensor:131]: 'Temperature': Sending state 27.48264 °C with 1 decimals of accuracy
[23:22:20.617][D][nextion:547]: Touch PRESS: page 1 comp 4
[23:22:20.622][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:20.627][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:20.789][D][nextion:547]: Touch RELEASE: page 1 comp 4
[23:22:20.793][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:20.798][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:20.803][D][text_sensor:069]: 'NSPanel local event': Sending state '{"page": "home", "event": "short_click", "component": "indr_temp"}'
[23:22:20.807][C][nspanel.core:043]:   Free heap:
[23:22:20.812][C][nspanel.core:046]:     Internal:   126824 bytes (37.9%)
[23:22:20.818][C][nspanel.core:056]:     PSRAM:     2001432 bytes (96.0%)
[23:22:20.824][D][nspanel.hw.display:235]: Send click event to Home Assistant
[23:22:20.832][D][nspanel.hw.display:244]: Home Assistant click event sent
[23:22:20.840][D][text_sensor:069]: 'Detailed Entity': Sending state 'embedded_climate'
[23:22:20.857][D][nextion_textsensor:014]: Text sensor: localevent='{"page": "home", "event": "short_click", "component": "indr_temp"}'
[23:22:20.863][D][nextion:562]: New page: 7
[23:22:20.869][I][nspanel.hw.display:063]: Page changed: 'home'->'climate'
[23:22:20.874][D][text_sensor:069]: 'Current Page': Sending state 'climate'
[23:22:20.880][D][nspanel.hw.display:320]: Entity shown: embedded_climate
[23:22:20.912][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:20.917][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:21.656][D][nextion:547]: Touch PRESS: page 7 comp 37
[23:22:21.661][D][script:088]: Script 'timer_page' restarting (mode: restart)
[23:22:21.668][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:21.673][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:21.683][D][nextion:562]: New page: 1
[23:22:21.687][I][nspanel.hw.display:063]: Page changed: 'climate'->'home'
[23:22:21.693][D][text_sensor:069]: 'Current Page': Sending state 'home'
[23:22:21.698][D][text_sensor:069]: 'Detailed Entity': Sending state ''
[23:22:21.732][D][script:088]: Script 'timer_page' restarting (mode: restart)
[23:22:21.736][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:21.742][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:21.839][D][script:088]: Script 'refresh_hardware_buttons_bars_with_delay' restarting (mode: restart)
[23:22:22.215][D][nspanel.boot:324]: Boot event response (from Blueprint) was successful
[23:22:22.283][D][nextion:547]: Touch PRESS: page 1 comp 3
[23:22:22.287][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:22.292][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:22.372][D][nextion:547]: Touch RELEASE: page 1 comp 3
[23:22:22.380][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:22.384][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:22.949][D][nextion:547]: Touch PRESS: page 1 comp 0
[23:22:22.949][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:22.949][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:23.107][D][nextion:547]: Touch RELEASE: page 1 comp 0
[23:22:23.107][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:23.107][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:23.499][D][nextion:547]: Touch PRESS: page 1 comp 31
[23:22:23.507][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:23.530][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:23.630][D][nextion:547]: Touch RELEASE: page 1 comp 31
[23:22:23.635][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[23:22:23.640][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[23:22:23.653][D][text_sensor:069]: 'NSPanel local event': Sending state '{"page": "home", "event": "short_click", "component": "button07"}'
[23:22:23.657][C][nspanel.core:043]:   Free heap:
[23:22:23.664][C][nspanel.core:046]:     Internal:   126896 bytes (37.9%)
[23:22:23.668][C][nspanel.core:056]:     PSRAM:     2008912 bytes (96.4%)
[23:22:23.678][D][nspanel.hw.display:235]: Send click event to Home Assistant
[23:22:23.688][D][nspanel.hw.display:244]: Home Assistant click event sent
[23:22:23.703][D][nextion_textsensor:014]: Text sensor: localevent='{"page": "home", "event": "short_click", "component": "button07"}'
[23:22:34.244][I][safe_mode:042]: Boot seems successful; resetting boot loop counter
```

### Home Assistant Logs

```text
2025-09-20 23:32:23.639 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: homeassistant.helpers.template.Wrapper object has no element 0 when rendering '{{ last_click_button[0] }}'
2025-09-20 23:32:23.639 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'entity' when rendering '{{ last_click_button.entity }}'
```

**Comment by Bascht74** [comment]
blueprint condig:

```
alias: NS Panel Wohnzimmer
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: a07a5efb60045494c95a5472332d092b
    language: de
    weather_entity: weather.zuhause
    outdoortemp: sensor.thermometer_ausen_carport_temperature
    qrcode_label: "..."
    qrcode_value: WIFI:S:Lotz_Gast;T:;P:;;
    left_button_name: Terr.  öffnen
    left_button_hold_select: Custom Action
    right_button_name: Terr.  schließen
    button_pages_icon_size: "10"
    button_page01_label: Lampen
    entity01: light.lampe_eg_wohnzimmer_wandlampen
    entity01_name: Wandlampen
    entity02: light.lampe_eg_wohnzimmer_decke
    entity02_name: Decke
    entity03: light.lampe_eg_wohnzimmer_esstisch
    entity03_name: Esstisch
    entity03_icon: mdi:chandelier
    entity04: light.lampe_eg_wohnzimmer_sideboard
    entity04_name: Sideboard
    entity05: light.lampe_eg_wohnzimmer_fenster_2
    entity05_name: Fernseher links
    screensaver_display_time: true
    screensaver_display_time_font_size: "11"
    decimal_separator: ","
    climate: climate.panel_eg_wohnzimmer_thermostat
    climate_chip_always_visible: true
    qrcode_enabled: true
    home_outdoor_temp_font: "4"
    button_page02_label: Rollos
    entity09: cover.rollo_eg_wohnzimmer_links1_cover_1
    entity09_name: Links außen
    entity10: cover.rollo_eg_wohnzimmer_links2_cover_1
    entity10_name: Links
    entity11: cover.rollo_eg_wohnzimmer_terrasse_cover_s
    entity11_name: Terrasse
    entity12: cover.rollo_eg_wohnzimmer_rechts1_cover_1
    entity12_name: Rechts
    entity13: cover.rollo_eg_wohnzimmer_rechts2_cover_1
    entity13_name: Rechts außen
    entity14: cover.rollo_eg_wohnzimmer_fenster_cover_1
    entity14_name: Fenster
    entity15: cover.markise_aussen_terrasse_cover
    entity15_name: Markise
    entity15_icon: mdi:awning-outline
    entity16: cover.rollos_eg_wohnzimmer_alle
    entity16_name: Alle WZ-Rollos
    entity16_icon: mdi:window-shutter-auto
    entity17_confirm: false
    domain_automation_button_action: trigger
    home_custom_button01: cover.rollo_eg_wohnzimmer_terrasse_cover_s
    home_value01: cover.rollos_eg_wohnzimmer_alle
    timezone: Europe/Berlin (CET-1CEST,M3.5.0,M10.5.0/3)
    indoortemp: sensor.panel_eg_wohnzimmer_temperatur
    hw_button_bar_left_always_show: true
    hw_button_bar_right_always_show: true
    hw_buttons_bar_color_off:
      - 31
      - 169
      - 255
    left_button_hold_custom_action:
      - data:
          entity: cover.rollo_eg_wohnzimmer_terrasse_cover_1
          back_page: buttonpage01
        action: esphome.panel_eg_wohnzimmer_entity_details_show
    right_button_hold_select: Custom Action
    right_button_hold_custom_action:
      - data:
          entity: cover.rollo_eg_wohnzimmer_terrasse_cover_1
          back_page: buttonpage01
        action: esphome.panel_eg_wohnzimmer_entity_details_show
    home_custom_button02: cover.markise_aussen_terrasse_cover_1
    button_page04_label: Navigation TEST
    entity25_name: Lichter
    entity25_icon: mdi:lightbulb-group
    entity25: input_button.panel
    entity26: input_button.panel
    entity26_name: Rollos
    entity27_icon: ""
    entity28_icon: ""
    entity29: input_button.panel
    entity29_name: Gäste WLAN
    entity29_icon: mdi:wifi
    entity30: media_player.appletv_wohnzimmer
    entity30_name: AppleTV
    entity30_icon: mdi:youtube-tv
    entity31_icon: ""
    entity27_confirm: true
    entity32: input_button.panel
    entity32_name: Infos
    entity32_icon: mdi:information-box
    home_custom_button01_name: Terrasse
    home_custom_button02_icon: mdi:awning
    home_custom_button02_name: Markise
    home_custom_button03: light.lampe_eg_wohnzimmer_decke
    home_custom_button03_name: Decke
    home_custom_button03_icon: mdi:ceiling-light
    home_custom_button04: light.lampe_eg_wohnzimmer_esstisch
    home_custom_button04_icon: mdi:chandelier
    home_custom_button04_name: Esstisch
    home_custom_button05: light.lampe_eg_wohnzimmer_wandlampen
    home_custom_button05_icon: mdi:coach-lamp
    home_custom_button05_name: Wandlampen
    home_custom_button06: light.lampe_eg_wohnzimmer_sideboard
    home_custom_button06_icon: mdi:alarm-light-outline
    home_custom_button06_name: Sideboard
    alarm: light.lampe_eg_wohnzimmer_fernseher_led
    home_custom_button07_icon: mdi:television-ambient-light
    home_custom_button07_name: Fernseher
    hw_buttons_bars_pages:
      - "2"
    entity01_icon: mdi:coach-lamp
    entity01_icon_color:
      - 250
      - 229
      - 0
    entity02_icon: mdi:ceiling-light-multiple
    entity02_icon_color:
      - 250
      - 229
      - 0
    entity03_icon_color:
      - 250
      - 229
      - 0
    entity04_icon: mdi:alarm-light-outline
    entity04_icon_color:
      - 250
      - 229
      - 0
    entity05_icon: mdi:aurora
    entity05_icon_color:
      - 250
      - 229
      - 0
    button_page03_label: Sonstiges
    entity17: climate.panel_eg_wohnzimmer_thermostat
    entity17_name: Klima
    entity17_icon: mdi:home-thermometer
    entity17_icon_color:
      - 250
      - 0
      - 0
    entity18: remote.harmonyhub_eg_wohnzimmer
    entity18_name: Fernseher anschalten
    entity18_icon: mdi:television
    entity19_name: Essen rufen
    entity19: script.kinder_uber_essen_informieren
    entity19_icon: mdi:food
    entity20: alarm_control_panel.master
    entity20_name: Alarm
    entity20_icon: ""
    screensaver_display_time_font_color:
      - 64
      - 0
      - 4
    icon_color_fallback_on:
      - 255
      - 221
      - 0

```

**Comment by edwardtfn** [comment]
This is odd... It is detecting the touch on the elements before detecting the swipe. 🤔

**Comment by Eric1980** [comment]
I have the same problem with my NSpanels.

**Comment by edwardtfn** [comment]
I need one info from your panel that you probably can collect without using the sliding...
Please press the time area until it jumps to the settings page. When on that page, please press an empty area for 5s until you get to a new page with lots of values in your page (I know it's annoying slow page creation, you should press on the screen from time to time to oayse/continue so it will prevent the fallback to Home page).
I'm interest on the value for "api".

**Comment by Bascht74** [comment]
<img width="1058" height="771" alt="Image" src="https://github.com/user-attachments/assets/fc7eb29c-322e-479c-958c-49a386cdbfb2" />

**Comment by Eric1980** [comment]
I don't know what the problem was for me but the error is fixed. Panel is working like a charm on 4.3.33

**Comment by marsh4200** [comment]
i have given up on the wackymas blueprint "wacky"  it has no support and i lost 15 ns panels in my place after updated the tft file its still dont work some after the update keep restarting now   ans the rest are with tft 000.000   no matter if i solder and load the tft file the lastest WITH THE LASTEST BLUEPRINT FAILS    HONESTLY GIVE THIS A 1 OUT 10  ITS THE WORST       IF ANY ONE WANTS FREE NS PANEL SOME BRICKED FOR FREE LET ME KNOW

**Comment by Bascht74** [comment]
> I don't know what the problem was for me but the error is fixed. Panel is working like a charm on 4.3.33

I have that Version on them, too

<img width="1170" height="1028" alt="Image" src="https://github.com/user-attachments/assets/a373d936-b86e-43cc-94aa-b30d5fe53747" />

**Comment by Bascht74** [comment]
What I found out: 
Swiping is broken on the homepage.

If I click on the weather, the weather page opens and swipe is posible there...
So ther must be something odd happening...

Homepage: 
```
[22:25:34.210][D][text_sensor:069]: 'Current Page': Sending state 'home'
[22:25:34.216][D][text_sensor:069]: 'Detailed Entity': Sending state ''
[22:25:34.251][D][script:088]: Script 'timer_page' restarting (mode: restart)
[22:25:34.256][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[22:25:34.263][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[22:25:34.345][D][script:088]: Script 'refresh_hardware_buttons_bars_with_delay' restarting (mode: restart)
[22:25:35.579][D][nextion:547]: Touch PRESS: page 1 comp 26
[22:25:35.582][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[22:25:35.588][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[22:25:35.780][D][nextion:547]: Touch RELEASE: page 1 comp 26
[22:25:35.785][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[22:25:35.790][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
```

Weather page: 
```
[22:25:33.016][D][text_sensor:069]: 'Current Page': Sending state 'weather01'
[22:25:33.022][D][text_sensor:069]: 'Detailed Entity': Sending state ''
[22:25:33.058][D][script:088]: Script 'timer_page' restarting (mode: restart)
[22:25:33.064][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[22:25:33.069][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[22:25:33.161][D][script:088]: Script 'refresh_hardware_buttons_bars_with_delay' restarting (mode: restart)
[22:25:33.301][D][nextion:547]: Touch PRESS: page 2 comp 0
[22:25:33.318][D][script:088]: Script 'timer_page' restarting (mode: restart)
[22:25:33.320][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[22:25:33.320][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[22:25:33.459][D][nextion:547]: Touch RELEASE: page 2 comp 0
[22:25:33.472][D][script:088]: Script 'timer_page' restarting (mode: restart)
[22:25:33.479][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[22:25:33.479][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[22:25:33.491][D][nextion:562]: New page: 6
[22:25:33.493][I][nspanel.hw.display:063]: Page changed: 'weather01'->'weather05'

```

**Comment by Bascht74** [comment]
@edwardtfn I hope you don't mind asking if there is any progress on that issue? What does `api: 1` mean?

**Comment by bennodepenno** [comment]
Hi, I seem to have a similar issue with my NSPanels (3) where swiping left/right does not reveal the other menus. I'm also missing the icons in the top bar (chips, entities). During the boot of the device I noticed:

```
[14:31:21.555][W][component:443]: script took a long time for an operation (145 ms)
[14:31:21.574][W][component:446]: Components should block for at most 30 ms
[14:31:22.251][D][nspanel.core:785]: Blueprint progress: 29.0%
[14:31:22.364][D][nspanel.boot:334]: Boot: Check TFT version
[14:31:22.369][D][nspanel.core:338]: Versions:
[14:31:22.373][D][nspanel.core:339]:   Blueprint: 4.3.33
[14:31:22.377][D][nspanel.core:340]:   ESPHome:   4.3.33
[14:31:22.391][D][nspanel.core:341]:   TFT:       4.3.33
[14:31:23.271][D][nspanel.core:785]: Blueprint progress: 29.0%
[14:31:23.391][D][nspanel.core:374]: Check version completed
[14:31:24.276][D][nspanel.core:785]: Blueprint progress: 29.0%
[14:31:24.587][W][nspanel.base:109]: Waiting for the system to be ready before executing an action
[14:31:25.271][D][nspanel.core:785]: Blueprint progress: 35.5%
[14:31:26.282][D][nspanel.core:785]: Blueprint progress: 35.5%
[14:31:27.288][D][nspanel.boot:334]: Boot: Blueprint is ready
[14:31:27.345][D][script.boot_progress:359]: Progress: 48.4%
[14:31:27.363][D][nspanel.boot:334]: Boot: Set Home page elements
[14:31:27.540][D][script.boot_progress:359]: Progress: 48.4%
[14:31:27.576][D][nspanel.boot:334]: Boot: Wait to finish
[14:31:27.577][D][nspanel.boot:334]: Boot: Waiting for Blueprint
[14:31:27.582][D][nspanel.boot:334]: Boot: Blueprint is ready
[14:31:27.588][D][script.boot_progress:359]: Progress: 48.4%
[14:31:27.625][D][script.boot_progress:354]: Progress: Completed
```

The blueprint progress jumps from 48.4% to completed. Is this perhaps the reason not all screens are loaded into the NSPanel @edwardtfn ? @Bascht74  does the boot of you NSPanel show similar output?

**Comment by edwardtfn** [comment]
Hi, my apologies for the silent here. I was out last week.



> What does `api: 1` mean?

The `api` var contains the info about the status of the API connection. 0 when disconnected, or 1 when connected.
This is used as a protection on the swipe to avoid trying to open pages that depends on the API, like button pages.
```txt
if(api==0)
{
  page home
}
```


> The blueprint progress jumps from 48.4% to completed. Is this perhaps the reason not all screens are loaded into the NSPanel [@edwardtfn](https://github.com/edwardtfn) ?

All the pages are loaded into the TFT files, so those are there when your panel boots, regardless the information from the blueprint.
The Blueprint is completely loaded in your case. The point is what that is counted, using bits, to the last step is always around 50%. Something to be improved in the future.
It could be a counter, but the way it is I can know which steps are missing, and not only how many steps are missing. 😉 

I will look at this issue now. It is strange, as nothing related to this was changed. The Nextion firmware was updated and could be related, but still needing investigation.

It's a good info that it is working on page weather. Thanks for that log!!

**Comment by edwardtfn** [comment]
This should be fixed now.
Could you please update your system (ESPHome, TFT and Blueprint) to v4.3.34 and let me know?

**Comment by Bascht74** [comment]
Sorry, it still doesn't work on the main page. I will collect the nessesary infos.
I will try to find out, if there ist something different. 

@edwardtfn could you reopen?

**Comment by bennodepenno** [comment]
Hi, I can confirm too that with all versions updated to 4.3.34, menu swiping from main screen does not work. I've also noticed that the entities bullet icon isn't showing on the main screen. Pressing the weather icon does open a set of screens which can be swiped left and right. It's as if the panel does not have all the options loaded. This behavior is consistent across all three NSPanels I have in use. Please let me know if I need to provide additional information.

**Comment by edwardtfn** [comment]
> entities bullet icon isn't showing on the main screen

Could you please report that as another issue, so we keep track of?

**Comment by edwardtfn** [comment]
About the swipe issue on home page... I have a few questions:

1. What happens when you try to swipe? Nothing happens, or it understand as a click on some component and execute that action?
2. Are there areas on that page where the swipe works? I mean, if you swipe on the date/time area, will that work? What about the buttons area, or the weather icon area?
3. Trying to swipe faster will make a difference?

**Comment by Bascht74** [comment]
1. Click on component and execute Action (of there is one)
2. no
3. no, Speed doesn’t change the result.

**Comment by edwardtfn** [comment]
I cannot duplicate this issue... 😩

**Comment by bennodepenno** [comment]
Hi,

As I've experienced similar issues, I decided to start with a clean blueprint configuration. I've added a simple button page and saved the blueprint configuration. Swiping works.


alias: NSPanel test Zolder Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: fd970733d9cefa78143e6846e7d5e1f3
    qrcode_enabled: true
    qrcode_label: Wifi Guest network
    qrcode_value: WIFI:S:guest;T:WPA;P:sdfsdfsdwerw;;
    button_page01_label: One
    entity02: light.0x000d6ffffe9df699
    entity_page01_label: Entity one
    entities_entity01: person.amber_ter_haar
    entitypages_show_entities_icons: true


Could the blueprint configuration be causing the issue? (this might also be related to https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/2930.

@Bascht74 : would you be able to start with a clean blueprint (save the existing one for reference) and add the elements you need one by one using the gui to see if the swiping issue is still present?

**Comment by bennodepenno** [comment]
Hi, following up on my previous comment: I've disabled my existing blueprint and created a new one using the old one as a reference. Swiping the pages do work now as well as the icons shown in the top of the screen (chips). I'm not sure if it's an incompatibility with the 'old' blueprint configuration or if the old blueprint configuration was using entities which have been removed/changed.

**Comment by edwardtfn** [comment]
Wow!
This info pointed me to something I was missing...  On the image share earlier, I was focusing to the `api` value, but now just noticed the buttons pages are all set to 0l which means there's no page to show with the swipe:

> <img width="1058" height="771" alt="Image" src="https://github.com/user-attachments/assets/fc7eb29c-322e-479c-958c-49a386cdbfb2" />

This is probably something on the Blueprint side. This info is transmitted to Nextion during the panel's boot.

Could you please take a look at Home Assistant logs (Settings > System > Logs) for anything related to the automation with the issue?

**Comment by edwardtfn** [comment]
That one shared earlier about the button click isn't related to this issue.

**Comment by Bascht74** [comment]
I was thinking about being the blueprint as well but I was away so I couldn't test it. 
I think it is. 

In my case it was two entities the got unawailable / deleted. And these entities disabled the swiping function.

At these places:
```
alias: ...
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    climate: climate.panel_eg_wohnzimmer_thermostat
    indoortemp: sensor.panel_eg_wohnzimmer_temperatur
    entity17: climate.panel_eg_wohnzimmer_thermostat
```

@edwardtfn Sorry, that the root cause was on my side. But I didn't expect the devices behave in that way because of a entity id that got missing or unavailable. I think this should be handeled by the blueprint. if there is no entity behind a given entity id or the entity is unavailable --> treat as a "empty" entry for that setting.
I think that way you could dublicate this issue if you change some of the entity ids in one of your configs or set some entities "unavailable" via the devs-tools. Then restart the ESP (restart)

**Comment by Bascht74** [comment]
@bennodepenno Watch out for wrong settings in your original blueprint for you device. Track down entites that are "missing" (got deleted) or went "unavailable" (valid stat of an entity)...

**Comment by edwardtfn** [comment]
> I think this should be handeled by the blueprint.

I fully agree... But I need error logs to find where this check is failing.

I will try to simulate some of these cases here, but if you find something in your logs, please share here. 😉

**Comment by edwardtfn** [comment]
Could you please let me know if this issue persists with v4.3.42?

**Comment by Bascht74** [comment]
I came home this Night from work (other City) I Tested it and no more Problems. So Yes, closing it was Right. Looking forward to getting BT working again. Long way, but almost everything is better for me Right now with 4.2.42 compaired to the Order ones from June: faster responses, TFT-Upload now relieable, Auto Update, Script for the Buttons etc. Great Progress!!!!

**Comment by edwardtfn** [comment]
I'm trying Bluetooth right now with v4.3.45 (not released yet) and ESPHome v2025.11.0-dev (also not released) and it is working for the basic configuration (no add-ons):

<img width="808" height="836" alt="Image" src="https://github.com/user-attachments/assets/a3240267-a21b-4cf2-acf7-539e74c519b9" />

Memory on good levels, so I probably will be able to start testing the add-ons soon. 😉

**Comment by Bascht74** [comment]
Great to hear!

For me it is the climate-addon combined with BT, because I have an eternal
thermometer (the internal one is not very good - even after delta
calibration)


Am Mo., 20. Okt. 2025 um 02:53 Uhr schrieb Edward Firmo <
***@***.***>:
