### ISSUE TITLE
`Bug` Can't change a color on color wheel on light page

### ISSUE THREAD

**Issue by karolkoz83** [Blackymas/NSPanel_HA_Blueprint#2905]
### TFT Version

4.3.33

### Firmware Version

4.3.33

### Blueprint Version

4.3.33

### Panel Model

EU

### What is the bug?

After latest update I can't change the color of the bulb on light page by color wheel.
By HA directly there's no problem at all.
Does anyone faced with such a problem?

### Your Panel's YAML

```yaml

```

### ESPHome Logs

```text

```

### Home Assistant Logs

```text

```

**Comment by Herko28** [comment]
I experience the same problem on both NS panels after the update
the color wheel is visible in all lights but does not respond to touch.
the slidebar for the white light works well.
The brightness/light intensity slider also works well

**Comment by edwardtfn** [comment]
Could you please share the ESPHome logs from your -anel when you try to change the color?

**Comment by Herko28** [comment]
[logs_touchepanel-herko_logs.txt](https://github.com/user-attachments/files/22601853/logs_touchepanel-herko_logs.txt)

**Comment by edwardtfn** [comment]
Could you please try to collect another info?

Please go to Developer Tools, then select tab "Events".
On the box "Listen to events" type `esphome.nspanel_ha_blueprint` and then click "Start listening".
Go to your panel and try to set a color for a light.
Please share here the event with `key: rgb_color`.

**Comment by Fredzxda** [comment]
Same problem here

**Comment by Herko28** [comment]
Hello Edward,

Here's the event.
Thank you in advance for your help, time, and effort.

```log
event_type: esphome.nspanel_ha_blueprint
data:
  device_id: d08fa80c52be29c47828509e88a3a87a
  action: light.turn_on
  blue: "255"
  device_name: touchepanel_herko
  entity: light.test_led_spot
  esphome_version: 4.3.33
  green: "63"
  key: rgb_color
  red: "255"
  tag: nspanel.page.light
  type: action_call
origin: LOCAL
time_fired: "2025-09-30T06:34:22.394861+00:00"
context:
  id: 01K6CN8JSTNCPJVFN0BHR49KCJ
  parent_id: null
  user_id: null
```

**Comment by edwardtfn** [comment]
Thanks!!
Now I see the issue is on the blueprint side... 😉

**Comment by karolkoz83** [comment]
Thanks! Waiting for new release.

**Comment by edwardtfn** [comment]
This should be fixed now.
Could you please update your system (ESPHome, TFT and Blueprint) to v4.3.34 and let me know?

**Comment by Herko28** [comment]
Unfortunately, the update did not solve the problem.
TFT version 4.3.34
Firmware version 4.3.34
Blueprint version 4.3.34


```yaml
 event_type: esphome.nspanel_ha_blueprint
data:
  device_id: d08fa80c52be29c47828509e88a3a87a
  action: light.turn_on
  blue: "95"
  device_name: touchepanel_herko
  entity: light.test_led_spot
  esphome_version: 4.3.34
  green: "255"
  key: rgb_color
  red: "95"
  type: action_call
origin: LOCAL
time_fired: "2025-10-01T16:32:56.334800+00:00"
context:
  id: 01K6G9XA0EZ0JK6E0DQPH2T1EE
  parent_id: null
  user_id: null
```

```yaml
event_type: esphome.nspanel_ha_blueprint
data:
  device_id: d08fa80c52be29c47828509e88a3a87a
  action: light.turn_on
  blue: "135"
  device_name: touchepanel_herko
  entity: light.test_led_spot
  esphome_version: 4.3.34
  green: "95"
  key: rgb_color
  red: "255"
  type: action_call
origin: LOCAL
time_fired: "2025-10-01T16:32:54.250217+00:00"
context:
  id: 01K6G9X7ZAZYJXQZ4M47W39G3T
  parent_id: null
  user_id: null
```

[logs_touchepanel-herko_logs (2).txt](https://github.com/user-attachments/files/22644780/logs_touchepanel-herko_logs.2.txt)

**Comment by wojciechczyz** [comment]
Confirming this not to be fixed on 4.3.34, awaiting 4.3.34 :-)

**Comment by edwardtfn** [comment]
Could you please update your system (ESPHome, TFT and Blueprint) to v4.3.35 and let me know if the issue persists?

**Comment by wojciechczyz** [comment]
I just checked and with 4.3.36 the colour wheel works, but colour temperature fails :-(

```log
[11:25:03.129][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[11:25:03.229][D][text_sensor:069]: 'NSPanel local event': Sending state '{"page": "home", "event": "short_click", "component": "button01"}'
[11:25:03.232][C][nspanel.core:043]:   Free heap:
[11:25:03.237][C][nspanel.core:046]:     Internal:   135664 bytes (40.5%)
[11:25:03.241][C][nspanel.core:056]:     PSRAM:     2008980 bytes (96.4%)
[11:25:03.249][D][nspanel.hw.display:234]: Send click event to Home Assistant
[11:25:03.260][D][nspanel.hw.display:243]: Home Assistant click event sent
[11:25:03.276][D][nextion_textsensor:014]: Text sensor: localevent='{"page": "home", "event": "short_click", "component": "button01"}'
[11:25:03.302][D][text_sensor:069]: 'Detailed Entity': Sending state 'light.g150_globo_2'
[11:25:03.361][D][nextion:562]: New page: 10
[11:25:03.365][I][nspanel.hw.display:063]: Page changed: 'home'->'light'
[11:25:03.369][D][text_sensor:069]: 'Current Page': Sending state 'light'
[11:25:03.373][D][nspanel.hw.display:305]: Entity shown: light.g150_globo_2
[11:25:03.413][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[11:25:03.418][D][nspanel.hw.display:478]: Waking up on page: light
[11:25:03.422][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[11:25:04.175][D][nextion:547]: Touch PRESS: page 10 comp 18
[11:25:04.179][D][script:088]: Script 'timer_page' restarting (mode: restart)
[11:25:04.182][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[11:25:04.186][D][nspanel.hw.display:478]: Waking up on page: light
[11:25:04.191][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[11:25:04.292][D][nextion:547]: Touch RELEASE: page 10 comp 18
[11:25:04.296][D][script:088]: Script 'timer_page' restarting (mode: restart)
[11:25:04.300][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[11:25:04.314][D][nspanel.hw.display:478]: Waking up on page: light
[11:25:04.317][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[11:25:05.159][D][nextion:547]: Touch PRESS: page 10 comp 15
[11:25:05.163][D][script:088]: Script 'timer_page' restarting (mode: restart)
[11:25:05.167][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[11:25:05.171][D][nspanel.hw.display:478]: Waking up on page: light
[11:25:05.176][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[11:25:05.296][D][nextion:547]: Touch RELEASE: page 10 comp 15
[11:25:05.300][D][script:088]: Script 'timer_page' restarting (mode: restart)
[11:25:05.309][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[11:25:05.309][D][nspanel.hw.display:478]: Waking up on page: light
[11:25:05.314][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[11:25:05.325][D][text_sensor:069]: 'NSPanel local event': Sending state '{"page": "light", "key": "color_temp", "value": 404}'
[11:25:05.337][C][nspanel.core:043]:   Free heap:
[11:25:05.337][C][nspanel.core:046]:     Internal:   135612 bytes (40.5%)
[11:25:05.342][C][nspanel.core:056]:     PSRAM:     2007444 bytes (96.3%)
[11:25:05.346][D][nspanel.hw.display:730]: Missing 'event' key
[11:25:05.365][D][nextion_textsensor:014]: Text sensor: localevent='{"page": "light", "key": "color_temp", "value": 404}'
[11:25:06.648][D][nextion:547]: Touch PRESS: page 10 comp 15
[11:25:06.652][D][script:088]: Script 'timer_page' restarting (mode: restart)
[11:25:06.656][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[11:25:06.667][D][nspanel.hw.display:478]: Waking up on page: light
[11:25:06.667][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[11:25:06.869][D][nextion:547]: Touch RELEASE: page 10 comp 15
[11:25:06.871][D][script:088]: Script 'timer_page' restarting (mode: restart)
[11:25:06.872][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[11:25:06.876][D][nspanel.hw.display:478]: Waking up on page: light
[11:25:06.881][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[11:25:06.886][D][text_sensor:069]: 'NSPanel local event': Sending state '{"page": "light", "key": "color_temp", "value": 429}'
[11:25:06.890][C][nspanel.core:043]:   Free heap:
[11:25:06.897][C][nspanel.core:046]:     Internal:   135512 bytes (40.4%)
[11:25:06.903][C][nspanel.core:056]:     PSRAM:     2008940 bytes (96.4%)
[11:25:06.911][D][nspanel.hw.display:730]: Missing 'event' key
[11:25:06.925][D][nextion_textsensor:014]: Text sensor: localevent='{"page": "light", "key": "color_temp", "value": 429}'
[11:25:07.806][D][nextion:547]: Touch PRESS: page 10 comp 15
[11:25:07.810][D][script:088]: Script 'timer_page' restarting (mode: restart)
[11:25:07.814][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[11:25:07.821][D][nspanel.hw.display:478]: Waking up on page: light
[11:25:07.824][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[11:25:07.983][D][nextion:547]: Touch RELEASE: page 10 comp 15
[11:25:07.987][D][script:088]: Script 'timer_page' restarting (mode: restart)
[11:25:07.991][D][script:088]: Script 'timer_dim' restarting (mode: restart)
[11:25:07.996][D][nspanel.hw.display:478]: Waking up on page: light
[11:25:08.002][D][script:088]: Script 'timer_sleep' restarting (mode: restart)
[11:25:08.007][D][text_sensor:069]: 'NSPanel local event': Sending state '{"page": "light", "key": "color_temp", "value": 385}'
[11:25:08.011][C][nspanel.core:043]:   Free heap:
[11:25:08.018][C][nspanel.core:046]:     Internal:   135580 bytes (40.5%)
[11:25:08.021][C][nspanel.core:056]:     PSRAM:     2008940 bytes (96.4%)
[11:25:08.026][D][nspanel.hw.display:730]: Missing 'event' key
[11:25:08.051][D][nextion_textsensor:014]: Text sensor: localevent='{"page": "light", "key": "color_temp", "value": 385}'
[11:25:08.781][I][safe_mode:042]: Boot seems successful; resetting boot loop counter
[11:25:08.802][D][esp32.preferences:143]: Writing 1 items: 0 cached, 1 written, 0 failed
```

[INFO ESPHome 2025.9.log](https://github.com/user-attachments/files/22678165/INFO.ESPHome.2025.9.log)

**Comment by Herko28** [comment]
I experience the same as wojciechczyz after the update
brightness as colour temperature fails / colorwheel works fine
